import { TProduct } from "./productDataR";

export const featuredProducts: TProduct[] = [

  {
    id: 11009,
    name: "Dell Latitude 5420 Core i5 11th Gen",
    price: 36500,
    originalPrice: 42999,
    quantity: 1,
    stock: 5,
    images: {
      links: [
        "/accessories/laptop-types/Dell Latitude 5420 Core i5 11th Gen.png",
      ],
      imgCount: 4,
    },
    description:
      "High-performance business laptop with Intel Core i5 11th Gen, 16GB RAM, 256GB SSD, and a stunning 14-inch Full HD touch display.",
    category: "computers",
    subcategory: "laptop-types",
    brand: "Dell",
    reviews: [],
    rating: 4.7,
    specifications: [
      { key: "Processor", value: "Intel Core i5 11th Gen" },
      { key: "RAM", value: "16 GB DDR4" },
      { key: "Storage", value: "256 GB SSD" },
      { key: "Display", value: "14-inch Full HD Touch Screen" },
      { key: "Power Supply", value: "65W AC Adapter" },
      { key: "Brand", value: "Dell" },
      { key: "Series", value: "Latitude 5420" },
      { key: "Operating System", value: "Windows 10 Pro" },
      { key: "Graphics", value: "Intel Iris Xe Graphics" }
    ],
  },

  {
    id: 11010,
    name: "Dell Latitude 7420 Touch Core i7 11th Gen",
    price: 46000,
    originalPrice: 52999,
    quantity: 1,
    stock: 5,
    images: {
      links: [
        "/accessories/laptop-types/Dell Latitude 7420 Touch Core i7 11th Gen.png",
      ],
      imgCount: 5,
    },
    description:
      "Ultra-slim business laptop with Intel Core i7 11th Gen, 16GB RAM, 512GB SSD, and a stunning 14-inch Full HD touch display with backlit keyboard.",
    category: "computers",
    subcategory: "laptop-types",
    brand: "Dell",
    reviews: [],
    rating: 4.7,
    specifications: [
      { key: "Processor", value: "Intel Core i7 11th Gen" },
      { key: "RAM", value: "16 GB DDR4" },
      { key: "Storage", value: "512 GB SSD" },
      { key: "Display", value: "14-inch Full HD Touch Screen" },
      { key: "Keyboard", value: "Backlit Keyboard" },
      { key: "Power Supply", value: "Dell Original Adapter" },
      { key: "Brand", value: "Dell" },
      { key: "Series", value: "Latitude 7420" },
      { key: "Operating System", value: "Windows 11" },
      { key: "Graphics", value: "Intel Iris Xe Graphics" },
      { key: "Design", value: "Ultra-slim" }
    ],
  },
  
  {
    id: 110012,
    name: "hp 8200-6200 sff Core i5 2nd Gen",
    price: 13500,
    originalPrice: 25999,
    stock: 30,
    quantity: 1,
    images: {
      links: ["/accessories/laptop-types/hp 8200-6200 sff Core i5 2nd Gen.png"],
      imgCount: 2,
    },
    description:
      "Business-class laptop with Intel Core i5 2nd Gen, 8GB RAM, 256GB SSD, and a 18.5 inch LCD display in A+ condition with new mouse and keyboard.",
    category: "computers",
    subcategory: "laptop-types",
    brand: "Lenovo",
    reviews: [],
    rating: 4.4,
    specifications: [
      { key: "Processor", value: "Intel Core i5 2nd Gen" },
      { key: "RAM", value: "8GB" },
      { key: "Storage", value: "256GB SSD" },
      { key: "Display", value: "18.5 inch LCD (1920 x 1080)" },
      { key: "Graphics", value: "Intel UHD Graphics 620" },
      { key: "Operating System", value: "Windows 10 Pro" },
      { key: "Weight", value: "1.68 Kg" },
      { key: "Battery", value: "Up to 3 hours" },
      { key: "Ports", value: "USB-C, USB 3.0, HDMI, Ethernet" },
      { key: "Keyboard", value: "Backlit, spill-resistant" },
      {
        key: "Additional Features",
        value: "Spill-resistant keyboard, fingerprint reader",
      },
    ],
  },
  {
    id: 110011,
    name: "DELL LATITUDE 5490 Core i5 8th Gen",
    price: 21200,
    originalPrice: 25999,
    stock: 30,
    quantity: 1,
    images: {
      links: [
        "/accessories/laptop-types/DELL LATITUDE 5490 Core i5 8th Gen.png",
      ],
      imgCount: 3,
    },
    description:
      "Business-class laptop with Intel Core i5 8th Gen, 8GB RAM, 256GB SSD, and a 14-inch FHD display.",
    category: "computers",
    subcategory: "laptop-types",
    brand: "Lenovo",
    reviews: [],
    rating: 4.4,
    specifications: [
      { key: "Processor", value: "Intel Core i5 8th Gen" },
      { key: "RAM", value: "8GB" },
      { key: "Storage", value: "256GB SSD" },
      { key: "Display", value: "14-inch FHD (1920 x 1080)" },
      { key: "Graphics", value: "Intel UHD Graphics 620" },
      { key: "Operating System", value: "Windows 10 Pro" },
      { key: "Weight", value: "1.68 Kg" },
      { key: "Battery", value: "Up to 3 hours" },
      { key: "Ports", value: "USB-C, USB 3.0, HDMI, Ethernet" },
      { key: "Keyboard", value: "Backlit, spill-resistant" },
      {
        key: "Additional Features",
        value: "Spill-resistant keyboard, fingerprint reader",
      },
    ],
  },
  {
    id: 11001,
    name: "Lenovo ThinkPad L480 Core i5 8th Gen",
    price: 21200,
    originalPrice: 25999,
    stock: 30,
    quantity: 1,
    images: {
      links: [
        "/accessories/laptop-types/Lenovo ThinkPad L480 Core i5 8th Gen.png",
      ],
      imgCount: 3,
    },
    description:
      "Business-class laptop with Intel Core i5 8th Gen, 8GB RAM, 256GB SSD, and a 14-inch FHD display.",
    category: "computers",
    subcategory: "laptop-types",
    brand: "Lenovo",
    reviews: [],
    rating: 4.4,
    specifications: [
      { key: "Processor", value: "Intel Core i5 8th Gen" },
      { key: "RAM", value: "8GB" },
      { key: "Storage", value: "256GB SSD" },
      { key: "Display", value: "14-inch FHD (1920 x 1080)" },
      { key: "Graphics", value: "Intel UHD Graphics 620" },
      { key: "Operating System", value: "Windows 10 Pro" },
      { key: "Weight", value: "1.68 Kg" },
      { key: "Battery", value: "Up to 3 hours" },
      { key: "Ports", value: "USB-C, USB 3.0, HDMI, Ethernet" },
      { key: "Keyboard", value: "Backlit, spill-resistant" },
      {
        key: "Additional Features",
        value: "Spill-resistant keyboard, fingerprint reader",
      },
    ],
  },
  {
    id: 11005,
    name: "Lenovo Thinkpad L470 Business Laptop i5 7th gen",
    price: 18999,
    stock: 15,
    originalPrice: 23999,
    quantity: 1,
    images: {
      links: [
        "/accessories/laptop-types/Lenovo Thinkpad L470 Business Laptop i5 7th gen.png",
      ],
      imgCount: 3,
    },
    description:
      "High-performance business laptop with Intel Core i5 7th Gen, 8GB RAM, 256GB SSD, and a stunning 14-inch WQXGA display.",
    category: "computers",
    subcategory: "laptop-types",
    brand: "Lenovo",
    reviews: [],
    rating: 4.7,
    specifications: [
      { key: "Standing Screen Display Size", value: "14 Inches" },
      { key: "Screen Resolution", value: "1366 x 768 pixels" },
      { key: "Max Screen Resolution", value: "1366x768 Pixels" },
      { key: "Processor", value: "Core i5 7th Gen" },
      { key: "RAM", value: "8 GB DDR4" },
      { key: "Memory Speed", value: "2.3 GHz" },
      { key: "Hard Drive", value: "500 GB HDD" },
      { key: "Graphics Coprocessor", value: "Intel HD Graphics 520" },
      { key: "Card Description", value: "Integrated" },
      { key: "Graphics Card RAM Size", value: "4 GB" },
      { key: "Wireless Type", value: "Bluetooth" },
      { key: "Number of USB 3.0 Ports", value: "3" },
      { key: "Average Battery Life (in hours)", value: "13 Hours" },
      { key: "Brand", value: "Lenovo" },
      { key: "Series", value: "Lenovo Thinkpad" },

      { key: "Operating System", value: "Windows 10 Pro" },
      { key: "Item Weight", value: "3.59 pounds" },
      { key: "Product Dimensions", value: "3.2 x 12 x 16.7 inches" },
      { key: "Item Dimensions (LxWxH)", value: "3.2 x 12 x 16.7 inches" },
      { key: "Color", value: "Black" },
      { key: "Processor Brand", value: "Intel" },

      {
        key: "Batteries",
        value: "1 Lithium Polymer batteries required. (included)",
      },
    ],
  },
  {
    id: 11006,
    name: "Lenovo Thinkpad L460 Business Laptop i5 6th gen",
    price: 16999,
    stock: 10,
    originalPrice: 21999,
    quantity: 1,
    images: {
      links: [
        "/accessories/laptop-types/Lenovo Thinkpad L460 Business Laptop i5 6th gen.png",
      ],
      imgCount: 3,
    },
    description:
      "High-performance business laptop with Intel Core i5 6th Gen, 8GB RAM, 256GB SSD, and a stunning 14-inch WQXGA display.",
    category: "computers",
    subcategory: "laptop-types",
    brand: "Lenovo",
    reviews: [],
    rating: 4.7,
    specifications: [
      { key: "Standing Screen Display Size", value: "14 Inches" },
      { key: "Screen Resolution", value: "1366 x 768 pixels" },
      { key: "Max Screen Resolution", value: "1366x768 Pixels" },
      { key: "Processor", value: "Core i5 6th Gen" },
      { key: "RAM", value: "8 GB DDR4" },
      { key: "Memory Speed", value: "2.3 GHz" },
      { key: "Hard Drive", value: "500 GB HDD" },
      { key: "Graphics Coprocessor", value: "Intel HD Graphics 520" },
      { key: "Wireless Type", value: "Bluetooth" },
      { key: "Number of USB 3.0 Ports", value: "3" },
      { key: "Average Battery Life (in hours)", value: "3 Hours" },
      { key: "Brand", value: "Lenovo" },
      { key: "Series", value: "Lenovo Thinkpad" },
      { key: "Operating System", value: "Windows 10 Pro" },
      { key: "Item Weight", value: "3.59 pounds" },
      { key: "Color", value: "Black" },
      { key: "Processor Brand", value: "Intel" },
    ],
  },
  {
    id: 11007,
    name: "Lenovo V330-14IKB 81B0 i5 7th gen",
    price: 13000,
    stock: 2,
    originalPrice: 17999,

    quantity: 1,
    images: {
      links: [
        "/accessories/laptop-types/Lenovo V330-14IKB 81B0 i5 7th gen.png",
      ],
      imgCount: 3,
    },
    description:
      "High-performance business laptop with Intel Core i5 7th Gen, 8GB RAM, 256GB SSD, and a stunning 14-inch WQXGA display.",
    category: "computers",
    subcategory: "laptop-types",
    brand: "Lenovo",
    reviews: [],
    rating: 4.7,
    specifications: [
      { key: "Processor", value: "Intel Core i5 7200U / up to 3.1 GHz" },
      { key: "Operating System", value: "Win 10 Pro 64-bit" },
      { key: "Graphics", value: "HD Graphics 620" },
      { key: "RAM", value: "8 GB" },
      { key: "Storage", value: "256 GB SSD" },
      { key: "Display", value: '14" TN 1920 x 1080 (Full HD)' },
      { key: "Ethernet", value: "Ethernet, Fast Ethernet, Gigabit Ethernet" },
      { key: "Wi-Fi Standard", value: "Wi-Fi 5" },
      { key: "Color", value: "Iron Gray" },
      { key: "Keyboard", value: "US" },
    ],
  },
  {
    id: 11008,
    name: "Dell Latitude E7440 14 Inch LED Ultrabook - Intel Core i5 4th gen",
    price: 15000,
    originalPrice: 17999,
    quantity: 1,
    stock: 2,
    images: {
      links: [
        "/accessories/laptop-types/Dell Latitude E7440 14 Inch LED Ultrabook - Intel Core i5 4th gen.png",
      ],
      imgCount: 3,
    },
    description:
      "High-performance business laptop with Intel Core i5 4th Gen, 4GB RAM, 500GB SSD, and a stunning 14-inch WQXGA display.",
    category: "computers",
    subcategory: "laptop-types",
    brand: "Dell",
    reviews: [],
    rating: 4.7,
    specifications: [
      { key: "Standing Screen Display Size", value: "14 Inches" },
      { key: "Screen Resolution", value: "1366 x 768 pixels" },
      { key: "Max Screen Resolution", value: "1080 Pixels" },
      { key: "Processor", value: "GHz core i5" },
      { key: "RAM", value: "4 MB DDR3L" },
      { key: "Memory Speed", value: "1600 MHz" },
      { key: "Hard Drive", value: "500 GB SSD" },
      { key: "Graphics Coprocessor", value: "Intel HD Graphics" },
      { key: "Brand", value: "Dell" },
      { key: "Series", value: "Latitude 7440" },
      { key: "Operating System", value: "Windows 10 Pro" },
      { key: "Color", value: "Brown" },
      { key: "Processor Brand", value: "Intel" },
      { key: "Number of Processors", value: "1" },
      { key: "Computer Memory Type", value: "DDR3 SDRAM" },
    ],
  }
 
  // {
  //   id: 200012,
  //   name: "Dell Precision 7520 Intel Core i7 - 6th Gen",
  //   description: "High-end laptop with advanced computing power.",
  //   price: 99990,
  //   originalPrice: 123990,
  //   // discount: +(((80000 - 70000) / 80000) * 100).toFixed(1),
  //   category: "laptops",
  //   subcategory: "workstation",
  //   quantity: 1,
  //   stock: 10,
  //   brand: "MSI",

  //   rating: 4.8,
  //   reviews: [],
  //   images: {
  //     links: [
  //       "/accessories/workstation/Dell Precision 7520 Intel Core i7 - 6th Gen.png",
  //     ],
  //     imgCount: 3,
  //   },
  //   specifications: [
  //     { key: "Brand", value: "Dell" },
  //     { key: "Series", value: "Precesion 7520" },
  //     { key: "Colour", value: "black" },
  //     { key: "Form Factor", value: "Laptop" },
  //     { key: "Standing screen display size", value: "15.6 Inches" },
  //     { key: "Screen Resolution", value: "1920 x 1080 pixels" },
  //     { key: "Resolution", value: "Full HD (1920 X 1080) Pixels" },
  //     { key: "Package Dimensions", value: "20 x 20 x 10 cm; 2.2 kg" },
  //     { key: "Item model number", value: "Dell Precision 7520" },
  //     { key: "Processor Brand", value: "Intel" },
  //     { key: "Processor Type", value: "Core i6 6820HQ" },
  //     { key: "Processor Speed", value: "2.70 GHz" },
  //     { key: "Processor Count", value: "1" },
  //     { key: "RAM Size", value: "16" },
  //     { key: "Memory Technology", value: "DDR4" },
  //     { key: "Computer Memory Type", value: "DDR4 SDRAM" },
  //     { key: "Maximum Memory Supported", value: "32 GB" },
  //     { key: "Hard Drive Size", value: "512 GB" },
  //     { key: "Hard Disk Description", value: "SSD" },
  //     { key: "Audio Details", value: "Headphones" },
  //     { key: "Graphics Chipset Brand", value: "NVIDIA" },
  //     { key: "Graphics Card Description", value: "Dedicated" },
  //     { key: "Graphics RAM Type", value: "DDR SDRAM" },
  //     { key: "Graphics Card Ram Size", value: "4 GB" },
  //     { key: "Graphics Card Interface", value: "Integrated" },
  //     { key: "Connectivity Type", value: "Wi-Fi" },
  //     { key: "Wireless Type", value: "802.11bgn" },
  //     { key: "Number of USB 3.0 Ports", value: "4" },
  //     { key: "Optical Drive Type", value: "No Optical Drive" },
  //     { key: "Operating System", value: "Windows 10 Pro" },
  //     { key: "Are Batteries Included", value: "No" },
  //     {
  //       key: "Included Components",
  //       value: "Adaptor, Laptop, power Cable",
  //     },
  //     { key: "Item Weight", value: "2 kg 200 g" },
  //   ],
  // },
];
