// const products = [
//   {
//     id: 1001,
//     name: "Logitech B175 / Optical Tracking, 12-Months Battery Life, Ambidextrous Wireless Optical Mouse (2.4GHz Wireless, Black)",
//     price: 449,
//     quantity: 1,
// stock: 10,
//     images: {links:["/mouse.png"],
//     description:
//       "If you are looking for an ergonomically designed wireless mouse, then this Logitech product with 2.4 GHz of connectivity is ideal for you. Furthermore, it’s long-lasting battery lasts for up to 12 months, so you can work with ease and convenience.",
//     category: "accessories",
//     subcategory: "mouse",
//     brand: "Logitech",
//     reviews: [],
//     rating: 0,
//     specifications: [
//       { key: "Type", value: "Wireless" },
//       { key: "Connectivity", value: "Bluetooth" },
//       {
//         key: "Model Name",
//         value: "B175 / Optical Tracking, 12-Months Battery Life, Ambidextrous",
//       },
//       {
//         key: "System Requirements",
//         value: "Windows: XP, Vista, 7, Mac OS x 10.5, Linux Kernel 2.6",
//       },
//       {
//         key: "Sales Package",
//         value: "1 Mouse,1 Adapter(unifying receiver ready)",
//       },
//       { key: "Controls", value: "2 Buttons" },
//       { key: "Color", value: "Black" },
//       { key: "Part Number", value: "910002635" },
//     ],
//   },
//   {
//     id: 1002,
//     name: "HP X200 Wireless Optical Mouse (Black, 3 Buttons)",
//     price: 499,
//     quantity: 1,
// stock: 10,
//     images: {links:["/mouse.png"],
//     description:
//       "The HP X200 is a versatile wireless mouse with a 2.4 GHz connection for seamless performance. Its ergonomic design ensures comfortable use for extended periods.",
//     category: "accessories",
//     subcategory: "mouse",
//     brand: "HP",
//     reviews: [],
//     rating: 0,
//     specifications: [
//       { key: "Type", value: "Wireless" },
//       { key: "Connectivity", value: "2.4GHz Wireless" },
//       { key: "Model Name", value: "X200" },
//       {
//         key: "System Requirements",
//         value: "Windows 7, 8, 10, macOS 10.13 and above",
//       },
//       { key: "Sales Package", value: "Mouse, USB Receiver" },
//       { key: "Controls", value: "3 Buttons" },
//       { key: "Color", value: "Black" },
//       { key: "Part Number", value: "6VY95AA" },
//     ],
//   },
//   {
//     id: 1003,
//     name: "Dell WM118 Wireless Optical Mouse (Black, 3 Buttons)",
//     price: 550,
//     quantity: 1,
// stock: 10,
//     images: {links:["/mouse.png"],
//     description:
//       "Experience smooth navigation and exceptional precision with the Dell WM118 wireless mouse, designed for productivity and convenience.",
//     category: "accessories",
//     subcategory: "mouse",
//     brand: "dell",
//     reviews: [],
//     rating: 0,
//     specifications: [
//       { key: "Type", value: "Wireless" },
//       { key: "Connectivity", value: "2.4GHz Wireless" },
//       { key: "Model Name", value: "WM118" },
//       {
//         key: "System Requirements",
//         value: "Windows 7, 8, 10, Linux",
//       },
//       { key: "Sales Package", value: "Mouse, USB Receiver, User Manual" },
//       { key: "Controls", value: "3 Buttons" },
//       { key: "Color", value: "Black" },
//       { key: "Part Number", value: "570-AAIS" },
//     ],
//   },
//   {
//     id: 1004,
//     name: "Razer DeathAdder Essential Wired Gaming Mouse",
//     price: 1799,
//     quantity: 1,
// stock: 10,
//     images: {links:["/mouse.png"],
//     description:
//       "The Razer DeathAdder Essential is a must-have gaming mouse featuring a 6,400 DPI optical sensor, durable switches, and an ergonomic design for competitive gaming.",
//     category: "accessories",
//     subcategory: "mouse",
//     brand: "Razer",
//     reviews: [],
//     rating: 0,
//     specifications: [
//       { key: "Type", value: "Wired" },
//       { key: "Connectivity", value: "USB" },
//       { key: "Model Name", value: "DeathAdder Essential" },
//       { key: "Sensor", value: "6,400 DPI Optical Sensor" },
//       { key: "Sales Package", value: "Mouse, User Guide" },
//       { key: "Controls", value: "5 Programmable Buttons" },
//       { key: "Color", value: "Black" },
//       { key: "Part Number", value: "RZ01-02540100-R3U1" },
//     ],
//   },
// ];

// import { original } from "@reduxjs/toolkit";

export type TProduct = {
  id: number;
  stock: number;
  name: string;
  price: number;
  originalPrice: number;
  quantity: number;
  images: {
    imgCount: number;
    links: string[];
  };
  description: string;
  category: string;
  subcategory: string;
  brand: string;
  reviews: never[];
  rating: number;
  specifications: {
    key: string;
    value: string;
  }[];
};

export const allProducts = {
  accessories: [
    {
      id: 1,
      Category: "new-accesories",
      subcategory: "Mouse",
      products: [
 
        {
          id: 1001,
          name: "ZEBRONICS zeb-dash Wireless Optical Mouse",
          price: 400,
          originalPrice: 599,
          quantity: 1,
          stock: 10,
          images: { links: ["/mouse.png"], imgCount: 1 },
          description:
            "If you are looking for an ergonomically designed wireless mouse, then this Logitech product with 2.4 GHz of connectivity is ideal for you. Furthermore, it’s long-lasting battery lasts for up to 12 months, so you can work with ease and convenience.",
          category: "accessories",
          subcategory: "mouse",
          brand: "Zebronics",
          reviews: [],
          rating: 0,
          specifications: [
            { key: "Type", value: "Wireless" },
            { key: "Connectivity", value: "Bluetooth" },
            {
              key: "Model Name",
              value:
                "B175 / Optical Tracking, 12-Months Battery Life, Ambidextrous",
            },
            {
              key: "System Requirements",
              value: "Windows: XP, Vista, 7, Mac OS x 10.5, Linux Kernel 2.6",
            },
            {
              key: "Sales Package",
              value: "1 Mouse,1 Adapter(unifying receiver ready)",
            },
            { key: "Controls", value: "2 Buttons" },
            { key: "Color", value: "Black" },
            { key: "Part Number", value: "910002635" },
          ],
        },
        {
          id: 1002,
          name: "ZEBRONICS ZEB-WING Wired Optical Mouse",
          price: 250,
          originalPrice: 300,
          quantity: 1,
          stock: 10,
          images: { links: ["/mouse.png"], imgCount: 1 },
          description:
            "ZEBRONICS ZEB-WING Wired Optical Mouse's optical LED tracking and connected interface provide dependable performance. Its accurate 1000 dpi optical tracking increases efficiency at home or in the office. This mouse's two buttons and scroll wheel suit the contours of the hand for comfortable, long-term use that makes navigating simple. Plug it into a USB port to begin using it immediately. It is plug-and-play convenient and works with almost any computer that has a USB connection. The Dell Optical Mouse is perfect for use at home or in the workplace since it puts comfort, convenience, and dependability first. Its contemporary style fits in perfectly with any desktop configuration.",
          category: "accessories",
          subcategory: "mouse",
          brand: "Zebronics",
          reviews: [],
          rating: 0,
          specifications: [
            { key: "Type", value: "wired" },
            { key: "Connectivity", value: "2.4GHz Wireless" },
            { key: "Model Name", value: "MS 116-BK" },
            {
              key: "System Requirements",
              value: "Windows 7, 8, 10, macOS 10.13 and above",
            },
            { key: "Sales Package", value: "Mouse" },
            { key: "Color", value: "Black" },
            { key: "Part Number", value: "MS116-BK" },
          ],
        },
        // {
        //   id: 1003,
        //   name: "HP S1000 Silent - Wireless Optical Mouse",
        //   originalPrice: 899,
        //   price: 499,
        //   quantity: 1,
        // stock: 10,
        //   images: { links: ["/mouse.png"], imgCount: 1 },
        //   description:
        //     "Experience smooth navigation and exceptional precision with the HP S1000 Silent / Lightweight, upto 1600 DPI Wireless Optical Mouse, designed for productivity and convenience.",
        //   category: "accessories",
        //   subcategory: "mouse",
        //   brand: "HP",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Type", value: "Wireless" },
        //     { key: "Connectivity", value: "2.4GHz Wireless" },
        //     {
        //       key: "Model Name",
        //       value: "S1000 Silent / Lightweight, upto 1600 DPI",
        //     },
        //     {
        //       key: "System Requirements",
        //       value: "S1000 Silent / Lightweight, upto 1600 DPI",
        //     },
        //     { key: "Sales Package", value: "Mouse, USB Receiver" },
        //     { key: "Color", value: "Black" },
        //     { key: "Part Number", value: "7YA12PA#ACJ" },
        //   ],
        // },
        // {
        //   id: 1004,
        //   name: "DELL MS 116 Wired Optical Mouse Wired Optical Gaming Mouse",
        //   price: 399,
        //   originalPrice: 645,
        //   quantity: 1,
        // stock: 10,
        //   images: { links: ["/mouse.png"], imgCount: 1 },
        //   description:
        //     "DELL MS 116 Wired Optical Mouse Wired Optical Gaming Mouse is a must-have gaming mouse featuring a 6,400 DPI optical sensor, durable switches, and an ergonomic design for competitive gaming.",
        //   category: "accessories",
        //   subcategory: "mouse",
        //   brand: "Dell",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Type", value: "Wired" },
        //     { key: "Connectivity", value: "USB" },
        //     { key: "Model Name", value: "MS 116 Wired Optical Mouse" },
        //     { key: "Sales Package", value: "Mouse, User Guide" },
        //     { key: "Color", value: "Black" },
        //   ],
        // },
        // {
        //   id: 1005,
        //   name: "DELL WM118 1000DPI, with USB Nano Receiver, Optical Tracking",
        //   price: 649,
        //   originalPrice: 999,
        //   quantity: 1,
        // stock: 10,
        //   images: { links: ["/mouse.png"], imgCount: 1 },
        //   description:
        //     "DELL MS 116 Wired Optical Mouse Wired Optical Gaming Mouse is a must-have gaming mouse featuring a 6,400 DPI optical sensor, durable switches, and an ergonomic design for competitive gaming.",
        //   category: "accessories",
        //   subcategory: "mouse",
        //   brand: "Dell",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Type", value: "Wired" },
        //     { key: "Connectivity", value: "USB" },
        //     { key: "Model Name", value: "MS 116 Wired Optical Mouse" },
        //     { key: "Sales Package", value: "Mouse, User Guide" },
        //     { key: "Color", value: "Black" },
        //   ],
        // },
        // {
        //   id: 1006,
        //   name: "ZEBRONICS Wing Wired Optical Gaming Mouse",
        //   price: 200,
        //   originalPrice: 229,
        //   quantity: 1,
        // stock: 10,
        //   images: { links: ["/mouse.png"], imgCount: 1 },
        //   description:
        //     "ZEBRONICS Wing Wired Optical Gaming Mouse is a must-have gaming mouse featuring a 6,400 DPI optical sensor, durable switches, and an ergonomic design for competitive gaming.",
        //   category: "accessories",
        //   subcategory: "mouse",
        //   brand: "ZEBRONICS",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Type", value: "Wired" },
        //     { key: "Connectivity", value: "USB" },
        //     { key: "Model Name", value: "Wing" },
        //     { key: "Sales Package", value: "Mouse, User Guide" },
        //     { key: "Color", value: "Black" },
        //   ],
        // },
      ],
    },
    {
      id: 2,
      Category: "new-accesories",
      subcategory: "Keyboard",
      products: [
        // Keyboards
        {
          id: 2001,
          name: "ZEBRONICS Zeb-K35 Wired USB Desktop Keyboard",
          price: 400,
          originalPrice: 599,
          quantity: 1,
          stock: 10,
          images: { links: ["/keyboard.png"], imgCount: 1 },
          description:
            "ZEBRONICS Zeb-K35 Wired USB Desktop Keyboard is a sleek and compact keyboard with an ergonomic design for enhanced productivity.",
          category: "accessories",
          subcategory: "keyboard",
          brand: "ZEBRONICS",
          reviews: [],
          rating: 0,
          specifications: [
            { key: "Type", value: "Wired" },
            { key: "Connectivity", value: "USB" },
            { key: "Sales Package", value: "Keyboard, User Manual" },
            { key: "Color", value: "Black" },
          ],
        },
        // {
        //   id: 2002,
        //   name: "Ant Value FKBRI01 Wired USB Multi-device Keyboard",
        //   price: 209,
        //   originalPrice: 699,
        //   quantity: 1,
        // stock: 10,
        //   images: { links: ["/keyboard.png"], imgCount: 1 },
        //   description:
        //     "Ant Value FKBRI01 Wired USB Keyboard is a wired multimedia keyboard designed for quiet and comfortable typing, perfect for both work and play.",
        //   category: "accessories",
        //   subcategory: "keyboard",
        //   brand: "Ant Value",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Type", value: "Wired" },
        //     { key: "Connectivity", value: "USB" },
        //     { key: "Compatibility", value: "Windows, Linux" },
        //     { key: "Layout", value: "Full-size Keyboard" },
        //     { key: "Sales Package", value: "Keyboard, User Guide" },
        //     { key: "Color", value: "Black" },
        //   ],
        // },
        // {
        //   id: 2003,
        //   name: "ZEBRONICS Zeb-K25 Wired USB Desktop Keyboard Wired USB Desktop Keyboard",
        //   price: 356,
        //   originalPrice: 499,
        //   quantity: 1,
        // stock: 10,
        //   images: { links: ["/keyboard.png"], imgCount: 1 },
        //   description:
        //     "ZEBRONICS Zeb-K25 Wired USB Desktop Keyboard Wired USB Desktop Keyboard is a wired keyboard with stunning ergonomic keys for gaming enthusiasts.",
        //   category: "accessories",
        //   subcategory: "keyboard",
        //   brand: "ZEBRONICS",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Type", value: "Wired" },
        //     { key: "Connectivity", value: "USB" },
        //     { key: "Compatibility", value: "Windows" },
        //     { key: "Sales Package", value: "Keyboard, User Manual" },
        //     { key: "Color", value: "Black" },
        //   ],
        // },
        // {
        //   id: 2004,
        //   name: "DELL KB 216 Wired USB Desktop Keyboard",
        //   price: 569,
        //   originalPrice: 1020,
        //   quantity: 1,
        // stock: 10,
        //   images: { links: ["/keyboard.png"], imgCount: 1 },
        //   description:
        //     "Type fast and accomplish a number of tasks on your personal computer with the Dell KB 216 Wired USB Desktop Keyboard. The full layout of this keyboard features chiclet-style keys for comfortable and efficient typing",
        //   category: "accessories",
        //   subcategory: "keyboard",
        //   brand: "Dell",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Type", value: "Wired" },
        //     { key: "Connectivity", value: "USB" },
        //     { key: "Compatibility", value: "Windows, macOS" },
        //     { key: "Sales Package", value: "Keyboard, User Manual" },
        //     { key: "Color", value: "Black" },
        //   ],
        // },
        // {
        //   id: 2005,
        //   name: "DELL keyboard and mouse with usb wire Wired USB Desktop Keyboard",
        //   price: 1116,
        //   originalPrice: 1407,
        //   quantity: 1,
        // stock: 10,
        //   images: { links: ["/keyboard.png"], imgCount: 1 },
        //   description:
        //     "Type fast and accomplish a number of tasks on your personal computer with the Dell KB 216 Wired USB Desktop Keyboard. The full layout of this keyboard features chiclet-style keys for comfortable and efficient typing.",
        //   category: "accessories",
        //   subcategory: "keyboard",
        //   brand: "Dell",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Type", value: "Wired" },
        //     { key: "Connectivity", value: "USB" },
        //     { key: "Backlit", value: "RGB Lighting" },
        //     { key: "Compatibility", value: "Windows" },
        //     { key: "Sales Package", value: "Keyboard, User Manual" },
        //     { key: "Color", value: "Black" },
        //   ],
        // },
        // {
        //   id: 2006,
        //   name: "Portronics POR 2113 Wireless Laptop Keyboard",
        //   price: 849,
        //   originalPrice: 1999,
        //   quantity: 1,
        // stock: 10,
        //   images: { links: ["/keyboard.png"], imgCount: 1 },
        //   description:
        //     "Portronics POR 2113 Wireless Laptop Keyboard features Cherry MX Red switches, customizable RGB lighting, and an ultra-modern design.",
        //   category: "accessories",
        //   subcategory: "keyboard",
        //   brand: "dell",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Type", value: "Mechanical" },
        //     { key: "Connectivity", value: "Bluetooth" },
        //     { key: "Backlit", value: "RGB Lighting" },
        //     { key: "Compatibility", value: "Windows, macOS" },
        //     { key: "Sales Package", value: "Keyboard, User Manual" },
        //     { key: "Color", value: "Black" },
        //   ],
        // },
        // {
        //   id: 2007,
        //   name: "ZEBRONICS K-35 Wired USB Multi-device Keyboard",
        //   price: 325,
        //   originalPrice: 449,
        //   quantity: 1,
        // stock: 10,
        //   images: { links: ["/keyboard.png"], imgCount: 1 },
        //   description:
        //     "The HP Omen Sequencer offers mechanical keys, customizable RGB, and robust build quality for gaming enthusiasts.",
        //   category: "accessories",
        //   subcategory: "keyboard",
        //   brand: "ZEBRONICS",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Type", value: "Mechanical" },
        //     { key: "Connectivity", value: "USB" },
        //     { key: "Compatibility", value: "Windows" },
        //     { key: "Sales Package", value: "Keyboard, User Manual" },
        //     { key: "Color", value: "Black" },
        //   ],
        // },
        // {
        //   id: 2008,
        //   name: "ZEBRONICS Zeb-Companion 107 Wireless Keyboard and Mouse Combo",
        //   price: 1499,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/keyboard.png"],
        //   description:
        //     "The ZEBRONICS Zeb-Companion 107 combo includes a wireless keyboard and mouse with sleek design and reliable performance.",
        //   category: "accessories",
        //   subcategory: "keyboard",
        //   brand: "ZEBRONICS",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Type", value: "Wireless" },
        //     { key: "Connectivity", value: "2.4 GHz Wireless" },
        //     { key: "Compatibility", value: "Windows, macOS" },
        //     { key: "Sales Package", value: "Keyboard, Mouse, USB Receiver" },
        //     { key: "Color", value: "Black" },
        //   ],
        // },
      ],
    },
    {
      id: 3,
      Category: "new-accesories",
      subcategory: "RAM",
      products: [
        // RAMs
        // {
        //   id: 3001,
        //   name: "Consistent 1600 DDR3 8 GB",
        //   price: 615,
        //   originalPrice: 2999,
        //   quantity: 1,
        // stock: 10,
        //   images: { links: ["/ram.png"], imgCount: 1 },
        //   description:
        //     "Corsair Vengeance LPX is designed for high-performance overclocking with an aluminum heat spreader for faster heat dissipation.",
        //   category: "accessories",
        //   subcategory: "ram",
        //   brand: "Consistent",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Capacity", value: "8GB" },
        //     { key: "Type", value: "DDR3" },
        //     { key: "Speed", value: "1600MHz" },
        //     { key: "Warranty", value: "Limited Lifetime" },
        //     { key: "Compatible Device", value: "PC" },
        //     { key: "Series", value: "1600" },
        //     { key: "Service Type", value: "3 Years Replacement Warranty" },
        //   ],
        // },
        // {
        //   id: 3002,
        //   name: "Hynix 1600Mhz DDR3 8 GB",
        //   price: 565,
        //   originalPrice: 4499,
        //   quantity: 1,
        // stock: 10,
        //   images: { links: ["/ram.png"], imgCount: 1 },
        //   description:
        //     "Kingston Fury Beast offers excellent performance and stunning design for both gamers and PC builders.",
        //   category: "accessories",
        //   subcategory: "ram",
        //   brand: "Hynix",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Capacity", value: "8GB" },
        //     { key: "Type", value: "DDR3" },
        //     { key: "Compatibile Device", value: "Laptop" },
        //     { key: "Speed", value: "1600MHz" },
        //   ],
        // },
        // {
        //   id: 3003,
        //   name: "HyperX Fury DDR3 8 GB",
        //   price: 810,
        //   originalPrice: 3900,
        //   quantity: 1,
        // stock: 10,
        //   images: { links: ["/ram.png"], imgCount: 1 },
        //   description:
        //     "G.SKILL Trident Z RGB RAM features customizable RGB lighting and exceptional performance for gaming enthusiasts.",
        //   category: "accessories",
        //   subcategory: "ram",
        //   brand: "G.SKILL",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Capacity", value: "8GB" },
        //     { key: "Type", value: "DDR3" },
        //     { key: "Speed", value: "1866MHz" },
        //     { key: "Warranty", value: "Limited Lifetime" },
        //   ],
        // },
        // {
        //   id: 3004,
        //   name: "Crucial CT DDR4 4 GB (Single Channel) PC SDRAM (CT4G4DFS8266)",
        //   price: 1325,
        //   originalPrice: 2300,
        //   quantity: 1,
        // stock: 10,
        //   images: { links: ["/ram.png"], imgCount: 1 },
        //   description:
        //     "ADATA XPG Spectrix D60G offers stylish design with RGB lighting and solid performance for gaming and multitasking.",
        //   category: "accessories",
        //   subcategory: "ram",
        //   brand: "ADATA",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Capacity", value: "4GB" },
        //     { key: "Type", value: "DDR4" },
        //     { key: "Speed", value: "2666 MHz" },
        //     { key: "Warranty", value: "10 Years Warranty" },
        //   ],
        // },
        // {
        //   id: 3005,
        //   name: "TeamGroup T-Force Vulcan Z 16GB DDR4 3200MHz RAM",
        //   price: 5999,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/ram.png"],
        //   description:
        //     "TeamGroup T-Force Vulcan Z offers reliable performance and an elegant design, perfect for gaming and high-performance PCs.",
        //   category: "accessories",
        //   subcategory: "ram",
        //   brand: "TeamGroup",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Capacity", value: "16GB" },
        //     { key: "Type", value: "DDR4" },
        //     { key: "Speed", value: "3200MHz" },
        //     { key: "Voltage", value: "1.35V" },
        //     { key: "Color", value: "Gray" },
        //     { key: "Warranty", value: "Limited Lifetime" },
        //   ],
        // },
        // {
        //   id: 3006,
        //   name: "Crucial Ballistix 8GB DDR4 3000MHz RAM",
        //   price: 2699,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/ram.png"],
        //   description:
        //     "Crucial Ballistix offers a great combination of speed and reliability for gaming and multitasking performance.",
        //   category: "accessories",
        //   subcategory: "ram",
        //   brand: "Crucial",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Capacity", value: "8GB" },
        //     { key: "Type", value: "DDR4" },
        //     { key: "Speed", value: "3000MHz" },
        //     { key: "Voltage", value: "1.35V" },
        //     { key: "Color", value: "Black" },
        //     { key: "Warranty", value: "Limited Lifetime" },
        //   ],
        // },
      ],
    },
    {
      id: 4,
      Category: "new-accesories",
      subcategory: "ups",
      products: [
        // APC UPS
        // {
        //   id: 4001,
        //   name: "Microtek Line Interactive UPS LEGEND 650 UPS",
        //   price: 1999,
        //   originalPrice: 2799,
        //   quantity: 1,
        // stock: 10,
        //   images: { links: ["/ups.png"], imgCount: 1 },
        //   description:
        //     "This Microtek UPS is a great choice for your computer system and its peripherals. Featuring a remarkable microprocessor, this computer UPS is highly reliable and protects your computer from electrical surges, voltage fluctuations and short circuits. ",
        //   category: "accessories",
        //   subcategory: "ups",
        //   brand: "Microtek",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Brand", value: "Microtek" },
        //     { key: "Capacity", value: "600VA" },
        //     { key: "Output Voltage", value: "230 V" },
        //     { key: "Output Power", value: "360 W" },
        //     { key: "Overload Protection", value: "Yes" },
        //     { key: "Cold Start", value: "Yes" },
        //   ],
        // },
        // {
        //   id: 4002,
        //   name: "Elista ELS-Ultra U725 360W - 650 VA UPS",
        //   price: 2079,
        //   originalPrice: 3599,
        //   quantity: 1,
        // stock: 10,
        //   images: { links: ["/ups.png"], imgCount: 1 },
        //   description:
        //     "Elista ELS Energy U725 UPS with built-in voltage regulator with super fast charging & DVR support to ensure a smooth working of your appliances. With high-tech auto restart on power resumption and high protection from overcharge, discharge, overload etc, this UPS is a must have power supply that you will need for efficient working.",
        //   category: "accessories",
        //   subcategory: "ups",
        //   brand: "Elista",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Brand", value: "Elista" },
        //     { key: "Capacity", value: "600VA" },
        //     { key: "Output Voltage", value: "230 V" },
        //     { key: "Output Power", value: "360 W" },
        //     { key: "Overload Protection", value: "Yes" },
        //     { key: "Cold Start", value: "Yes" },
        //   ],
        // },
        // CyberPower UPS
        // {
        //   id: 4003,
        //   name: "Frontech Force UPS Electra Plus 600VA-360W",
        //   price: 2199,
        //   originalPrice: 3500,
        //   quantity: 1,
        // stock: 10,
        //   images: { links: ["/ups.png"], imgCount: 1 },
        //   description:
        //     "Frontech FT 2564 Static Converter UPS offers excellent power protection with surge suppression, battery backup, and LCD display for real-time monitoring of the UPS status.",
        //   category: "accessories",
        //   subcategory: "ups",
        //   brand: "Frontech",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Capacity", value: "1500VA" },
        //     { key: "Output Power", value: "900W" },
        //     { key: "Input Voltage", value: "230V" },
        //   ],
        // },
        // {
        //   id: 4004,
        //   name: "Frontech FT 2564 Static Converter UPS",
        //   price: 2299,
        //   originalPrice: 4999,
        //   quantity: 1,
        // stock: 10,
        //   images: { links: ["/ups.png"], imgCount: 1 },
        //   description:
        //     "Frontech FT 2564 Static Converter UPS is a compact and reliable UPS with surge protection and battery backup to ensure your devices remain powered during an outage.",
        //   category: "accessories",
        //   subcategory: "ups",
        //   brand: "Frontech",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Capacity", value: "1000VA" },
        //     { key: "Output Power", value: "600W" },
        //     { key: "Input Voltage", value: "230V" },
        //     { key: "Battery Type", value: "Sealed Lead Acid" },
        //   ],
        // },
        // // Eaton UPS
        // {
        //   id: 4005,
        //   name: "Eaton 5S 700VA",
        //   price: 4999,
        //   originalPrice: 5499,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/ups.png"],
        //   description:
        //     "Eaton 5S 700VA is a compact and reliable UPS with LCD display and battery backup to protect your devices from power outages and surges.",
        //   category: "accessories",
        //   subcategory: "ups",
        //   brand: "Eaton",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Capacity", value: "700VA" },
        //     { key: "Output Power", value: "420W" },
        //     { key: "Input Voltage", value: "230V" },
        //     { key: "Battery Type", value: "Sealed Lead Acid" },
        //   ],
        // },
        // {
        //   id: 4006,
        //   name: "Eaton 5P 850VA",
        //   price: 8999,
        //   originalPrice: 9999,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/ups.png"],
        //   description:
        //     "Eaton 5P 850VA UPS provides reliable backup power and advanced surge protection with an easy-to-read LCD display.",
        //   category: "accessories",
        //   subcategory: "ups",
        //   brand: "Eaton",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Capacity", value: "850VA" },
        //     { key: "Output Power", value: "510W" },
        //     { key: "Input Voltage", value: "230V" },
        //     { key: "Battery Type", value: "Sealed Lead Acid" },
        //   ],
        // },
        // // Vertiv UPS
        // {
        //   id: 4007,
        //   name: "Vertiv Liebert ITA2 600VA",
        //   price: 2999,
        //   originalPrice: 3599,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/ups.png"],
        //   description:
        //     "Vertiv Liebert ITA2 600VA is a reliable and compact UPS with a sleek design, ideal for small offices and home use, providing reliable backup power.",
        //   category: "accessories",
        //   subcategory: "ups",
        //   brand: "Vertiv",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Capacity", value: "600VA" },
        //     { key: "Output Power", value: "360W" },
        //     { key: "Input Voltage", value: "230V" },
        //     { key: "Battery Type", value: "Sealed Lead Acid" },
        //   ],
        // },
        // {
        //   id: 4008,
        //   name: "Vertiv Liebert PSA 1000VA",
        //   price: 6499,
        //   originalPrice: 7499,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/ups.png"],
        //   description:
        //     "Vertiv Liebert PSA 1000VA is a reliable UPS that offers backup power, surge protection, and an easy-to-use interface for home and small office environments.",
        //   category: "accessories",
        //   subcategory: "ups",
        //   brand: "Vertiv",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Capacity", value: "1000VA" },
        //     { key: "Output Power", value: "600W" },
        //     { key: "Input Voltage", value: "230V" },
        //     { key: "Battery Type", value: "Sealed Lead Acid" },
        //   ],
        // },
      ],
    },
    {
      id: 5,
      Category: "new-accesories",
      subcategory: "pendrives",
      products: [
        // SanDisk Pen Drives
        {
          id: 5001,
          name: "SanDisk Cruzer Blade 32GB USB Flash Drive",
          price: 480,
          originalPrice: 599,
          quantity: 1,
          stock: 10,
          images: { links: ["/pendrive.png"], imgCount: 1 },
          description:
            "SanDisk Cruzer Blade 32GB USB Flash Drive Pen Drive offers fast data transfer speeds with a sleek design and high capacity.",
          category: "accessories",
          subcategory: "pendrives",
          brand: "Sandisk",
          reviews: [],
          rating: 0,
          specifications: [
            { key: "Capacity", value: "32GB" },
            { key: "USB Version", value: "USB 3.0" },
            { key: "Transfer Speed", value: "150MB/s" },
            { key: "Compatibility", value: "Windows, macOS, Linux" },
          ],
        },
        // {
        //   id: 5002,
        //   name: "Sandisk Cruzer Blade 16 GB Utility Pendrive",
        //   price: 249,
        //   originalPrice: 299,
        //   quantity: 1,
        // stock: 10,
        //   images: { links: ["/pendrive.png"], imgCount: 1 },
        //   description:
        //     "SanDisk Cruzer Blade 16GB USB 2.0 Pen Drive offers a compact design and reliable storage for your everyday needs.",
        //   category: "accessories",
        //   subcategory: "pendrives",
        //   brand: "Sandisk",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Capacity", value: "16GB" },
        //     { key: "USB Version", value: "USB 2.0" },
        //     { key: "Transfer Speed", value: "Up to 10MB/s" },
        //     { key: "Compatibility", value: "Windows, macOS" },
        //   ],
        // },

        // Kingston Pen Drives
        // {
        //   id: 5003,
        //   name: "KINGSTON DataTraveler Exodia M USB 3.2 Gen 1 64 Pen Drive",
        //   price: 599,
        //   originalPrice: 799,
        //   quantity: 1,
        // stock: 10,
        //   images: { links: ["/pendrive.png"], imgCount: 1 },
        //   description:
        //     "Kingston DataTraveler 100 G3 64GB USB 3.0 Pen Drive delivers high-speed transfers and large storage capacity for professionals and students.",
        //   category: "accessories",
        //   subcategory: "pendrives",
        //   brand: "Kingston",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Capacity", value: "64GB" },
        //     { key: "USB Version", value: "USB 3.0" },
        //     { key: "Transfer Speed", value: "Up to 100MB/s" },
        //     { key: "Compatibility", value: "Windows, macOS, Linux" },
        //   ],
        // },
        // {
        //   id: 5004,
        //   name: "Kingston DataTraveler 50 32GB USB 3.0 Pen Drive",
        //   price: 499,
        //   originalPrice: 599,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/pendrive.png"],
        //   description:
        //     "Kingston DataTraveler 50 32GB USB 3.0 Pen Drive offers fast data transfer speeds in a compact design, making it ideal for everyday use.",
        //   category: "accessories",
        //   subcategory: "pendrives",
        //   brand: "Kingston",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Capacity", value: "32GB" },
        //     { key: "USB Version", value: "USB 3.0" },
        //     { key: "Transfer Speed", value: "Up to 100MB/s" },
        //     { key: "Compatibility", value: "Windows, macOS, Linux" },
        //   ],
        // },

        // // Transcend Pen Drives
        // {
        //   id: 5005,
        //   name: "Transcend JetFlash 720 128GB USB 3.0 Pen Drive",
        //   price: 1499,
        //   originalPrice: 1799,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/pendrive.png"],
        //   description:
        //     "Transcend JetFlash 720 128GB USB 3.0 Pen Drive offers high-speed transfers and ample storage for large files, including videos and documents.",
        //   category: "accessories",
        //   subcategory: "pendrives",
        //   brand: "Transcend",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Capacity", value: "128GB" },
        //     { key: "USB Version", value: "USB 3.0" },
        //     { key: "Transfer Speed", value: "Up to 70MB/s" },
        //     { key: "Compatibility", value: "Windows, macOS, Linux" },
        //   ],
        // },
        // {
        //   id: 5006,
        //   name: "Transcend JetFlash 380 32GB USB 2.0 Pen Drive",
        //   price: 399,
        //   originalPrice: 499,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/pendrive.png"],
        //   description:
        //     "Transcend JetFlash 380 32GB USB 2.0 Pen Drive is a reliable option for storing and transferring files, perfect for everyday use with its user-friendly design.",
        //   category: "accessories",
        //   subcategory: "pendrives",
        //   brand: "Transcend",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Capacity", value: "32GB" },
        //     { key: "USB Version", value: "USB 2.0" },
        //     { key: "Transfer Speed", value: "Up to 15MB/s" },
        //     { key: "Compatibility", value: "Windows, macOS" },
        //   ],
        // },

        // // HP Pen Drives
        // {
        //   id: 5007,
        //   name: "HP v250w 64GB USB 2.0 Pen Drive",
        //   price: 599,
        //   originalPrice: 699,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/pendrive.png"],
        //   description:
        //     "HP v250w 64GB USB 2.0 Pen Drive offers ample storage with a simple design, perfect for transferring files quickly and securely.",
        //   category: "accessories",
        //   subcategory: "pendrives",
        //   brand: "HP",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Capacity", value: "64GB" },
        //     { key: "USB Version", value: "USB 2.0" },
        //     { key: "Transfer Speed", value: "Up to 25MB/s" },
        //     { key: "Compatibility", value: "Windows, macOS" },
        //   ],
        // },
        // {
        //   id: 5008,
        //   name: "HP x740w 128GB USB 3.0 Pen Drive",
        //   price: 1099,
        //   originalPrice: 1299,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/pendrive.png"],
        //   description:
        //     "HP x740w 128GB USB 3.0 Pen Drive is designed for fast file transfers, with a generous 128GB capacity to store your important data.",
        //   category: "accessories",
        //   subcategory: "pendrives",
        //   brand: "HP",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Capacity", value: "128GB" },
        //     { key: "USB Version", value: "USB 3.0" },
        //     { key: "Transfer Speed", value: "Up to 150MB/s" },
        //     { key: "Compatibility", value: "Windows, macOS, Linux" },
        //   ],
        // },
      ],
    },
    {
      id: 6,
      Category: "new-accesories",
      subcategory: "monitors",
      products: [
        // LG Monitors
        // {
        //   id: 6001,
        //   name: "Frontech 43.18 cm (17 inch) HD Monitor (1995)",
        //   price: 2499,
        //   originalPrice: 5000,
        //   quantity: 1,
        // stock: 10,
        //   images: { links: ["/monitor.png"], imgCount: 1 },
        //   description:
        //     "The LG 24MP59G offers excellent color accuracy and vibrant visuals with its Full HD IPS display, ideal for gaming and productivity.",
        //   category: "accessories",
        //   subcategory: "monitors",
        //   brand: "Frontech",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Model Name", value: "1995" },
        //     { key: "Color", value: "Black" },
        //     { key: "Display", value: "43.18 cm (17 inch) LED Display" },
        //     { key: "Backlight", value: "Non LED Backlit Backlight" },
        //     { key: "3D", value: "No" },
        //     { key: "Screen Resolution Type", value: "HD" },
        //     { key: "Sales Package", value: "1 unit" },
        //     { key: "Screen Form Factor", value: "Flat" },
        //     { key: "Display Features", value: "" },
        //     {
        //       key: "Maximum Refresh Rate",
        //       value: "60 Hz (Analog), 60 Hz (Digital)",
        //     },
        //     { key: "Response Time", value: "5 ms" },
        //   ],
        // },
        // {
        //   id: 6002,
        //   name: "Frontech 48.26 cm (19 inch) HD LED Backlit Monitor",
        //   price: 2530,
        //   originalPrice: 8500,
        //   quantity: 1,
        // stock: 10,
        //   images: { links: ["/monitor.png"], imgCount: 1 },
        //   description:
        //     "The LG Ultragear 27GN750 delivers an immersive gaming experience with its 1ms response time, 240Hz refresh rate, and vibrant colors.",
        //   category: "accessories",
        //   subcategory: "monitors",
        //   brand: "Frontech",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Number of Colors", value: "16.7 M Colors" },
        //     {
        //       key: "Maximum Refresh Rate",
        //       value: "60 Hz (Analog), 60 Hz (Digital)",
        //     },
        //     { key: "Response Time", value: "3 ms" },
        //     { key: "Brightness", value: "250 nits (2D)" },
        //     { key: "Model Name", value: "MON-0071" },
        //     { key: "Color", value: "Black" },
        //     {
        //       key: "Display",
        //       value: "48.26 cm (19 inch) LED Wide Screen Display",
        //     },
        //     { key: "Backlight", value: "LED Backlit Backlight" },
        //     { key: "Resolution", value: "1440×900 pixels" },
        //     { key: "3D", value: "No" },
        //     { key: "Screen Resolution Type", value: "HD" },
        //     {
        //       key: "Sales Package",
        //       value:
        //         "HDMI Cable= 1UNIT, Stand= 1 Unit, Power Cable= 1 Unit, LED Monitor= 1 Unit",
        //     },
        //     { key: "Screen Form Factor", value: "Flat" },
        //     { key: "Pixel Pitch", value: "0.2835 mm" },
        //   ],
        // },
        // Dell Monitors
        // {
        //   id: 6003,
        //   name: "LG M39 49.53 cm (19.5 inch) HD LED Backlit TN Panel Wall Mountable Monitor",
        //   price: 5399,
        //   originalPrice: 9600,
        //   quantity: 1,
        // stock: 10,
        //   images: { links: ["/monitor.png"], imgCount: 1 },
        //   description:
        //     "The Dell P2419H features a slim design with an ultra-thin bezel, offering Full HD resolution and exceptional color consistency with its IPS panel.",
        //   category: "accessories",
        //   subcategory: "monitors",
        //   brand: "LG",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Model Name", value: "20M39A" },
        //     { key: "Series", value: "M39" },
        //     { key: "Color", value: "Black" },
        //     { key: "Display", value: "49.53 cm (19.5 inch) LED Display" },
        //     { key: "Backlight", value: "LED Backlit Backlight" },
        //     { key: "Panel Type", value: "TN Panel" },
        //     { key: "Resolution", value: "1366 x 768 pixels" },
        //     { key: "3D", value: "No" },
        //     { key: "Screen Resolution Type", value: "HD" },
        //     {
        //       key: "Sales Package",
        //       value: "1 Monitor, Stand, Power Cable, Connectivity Cable",
        //     },
        //     { key: "Screen Form Factor", value: "Flat" },
        //   ],
        // },
        // {
        //   id: 6004,
        //   name: "LG 46.99 cm (18.5 inch) HD LED Backlit TN Panel Monitor",
        //   price: 5625,
        //   originalPrice: 9500,
        //   quantity: 1,
        // stock: 10,
        //   images: { links: ["/monitor.png"], imgCount: 1 },
        //   description:
        //     "LG 46.99 cm (18.5 inch) HD LED Backlit TN Panel Monitor with 144Hz refresh rate, providing a smooth and immersive gaming experience.",
        //   category: "accessories",
        //   subcategory: "monitors",
        //   brand: "LG",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Model Name", value: "19M38HB-B.BTRS" },
        //     { key: "Color", value: "Black" },
        //     {
        //       key: "Display",
        //       value: "46.99 cm (18.5 inch) LED Backlit Display",
        //     },
        //     { key: "Backlight", value: "LED Backlit Backlight" },
        //     { key: "Panel Type", value: "TN Panel" },
        //     { key: "Resolution", value: "1366 x 768 pixels" },
        //     { key: "3D", value: "No" },
        //     { key: "Screen Resolution Type", value: "HD" },
        //     {
        //       key: "Sales Package",
        //       value:
        //         "Monitor, Power Chord, D-sub, User Manual, Warranty Documents",
        //     },
        //     { key: "Screen Form Factor", value: "Flat" },
        //   ],
        // },
        // Samsung Monitors
        // {
        //   id: 6005,
        //   name: "SAMSUNG 55.88 cm (22 inch) Full HD VA Panel Monitor",
        //   price: 5899,
        //   originalPrice: 13700,
        //   quantity: 1,
        // stock: 10,
        //   images: { links: ["/monitor.png"], imgCount: 1 },
        //   description:
        //     "The Samsung monitor is an invitation to explore a new realm of visual excellence and comfort. Immerse yourself in a wide view that leaves no detail untouched, relish the depth of true definition that this VA Panel technology brings, and revel in the care this monitor has embedded to keep your eyes fresh and invigourated.",
        //   category: "accessories",
        //   subcategory: "monitors",
        //   brand: "Samsung",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Model Name", value: "LS22A334NHWXXL" },
        //     { key: "Color", value: "Black" },
        //     { key: "Display", value: "55.88 cm (22 inch) LED Display" },
        //     { key: "Panel Type", value: "VA Panel" },
        //     { key: "Screen Resolution Type", value: "Full HD" },
        //     {
        //       key: "Sales Package",
        //       value: "1 Monitor, Power Cable, HDMI Cable",
        //     },
        //     { key: "Screen Form Factor", value: "Flat" },
        //     {
        //       key: "Maximum Refresh Rate",
        //       value: "60 Hz (Analog), 60 Hz (Digital)",
        //     },
        //     { key: "Aspect Ratio", value: "16:09" },
        //     { key: "Response Time", value: "6.5 ms" },
        //   ],
        // },
        // {
        //   id: 6006,
        //   name: "Samsung LU28R550UQNXZA 28-Inch 4K UHD Monitor",
        //   price: 22999,
        //   originalPrice: 25999,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/monitor.png"],
        //   description:
        //     "The Samsung LU28R550UQNXZA is a 28-inch 4K UHD monitor with stunning picture quality, perfect for both work and gaming.",
        //   category: "accessories",
        //   subcategory: "monitors",
        //   brand: "Samsung",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Screen Size", value: "28 inches" },
        //     { key: "Resolution", value: "3840x2160 (4K UHD)" },
        //     { key: "Panel Type", value: "IPS" },
        //     { key: "Refresh Rate", value: "60Hz" },
        //     { key: "Connectivity", value: "HDMI, DisplayPort" },
        //   ],
        // },
        // // Acer Monitors
        // {
        //   id: 6007,
        //   name: "Acer KG241Y 23.8-Inch Full HD IPS Monitor",
        //   price: 8999,
        //   originalPrice: 10999,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/monitor.png"],
        //   description:
        //     "The Acer KG241Y offers a Full HD resolution and IPS technology for vibrant colors, perfect for home and office use.",
        //   category: "accessories",
        //   subcategory: "monitors",
        //   brand: "Acer",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Screen Size", value: "23.8 inches" },
        //     { key: "Resolution", value: "1920x1080 (Full HD)" },
        //     { key: "Panel Type", value: "IPS" },
        //     { key: "Refresh Rate", value: "75Hz" },
        //     { key: "Connectivity", value: "HDMI, VGA" },
        //   ],
        // },
        // {
        //   id: 6008,
        //   name: "Acer Predator XB273K 27-Inch 4K UHD Gaming Monitor",
        //   price: 59999,
        //   originalPrice: 69999,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/monitor.png"],
        //   description:
        //     "The Acer Predator XB273K offers 4K UHD resolution, a 144Hz refresh rate, and NVIDIA G-SYNC technology, designed for an immersive gaming experience.",
        //   category: "accessories",
        //   subcategory: "monitors",
        //   brand: "Acer",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Screen Size", value: "27 inches" },
        //     { key: "Resolution", value: "3840x2160 (4K UHD)" },
        //     { key: "Panel Type", value: "IPS" },
        //     { key: "Refresh Rate", value: "144Hz" },
        //     { key: "Connectivity", value: "HDMI, DisplayPort" },
        //   ],
        // },
      ],
    },
    {
      id: 7,
      Category: "new-accesories",
      subcategory: "cables",
      products: [
        // AmazonBasics Cables
        {
          id: 7001,
          name: "ZEBRONICS Haa1020 Hdmi 2.0 Cable - Hdmi Arc Enabled",
          price: 385,
          originalPrice: 599,
          quantity: 1,
          stock: 10,
          images: { links: ["/cables.png"], imgCount: 1 },
          description:
            "ZEBRONICS Haa1020 Hdmi 2.0 Cable - Hdmi Arc Enabled unique interms of design and multi-use and is positioned to provide the best comfort and performance while using. PVC material to make sure that the life of the cable is enhanced significantly. It comes with Charge & Sync Function. ",
          category: "accessories",
          subcategory: "cables",
          brand: "Zebronics",
          reviews: [],
          rating: 0,
          specifications: [
            { key: "Cable Length", value: "6 feet" },
            { key: "Cable Type", value: "HDMI" },
            { key: "Resolution", value: "4K" },
            { key: "Connector Type", value: "HDMI" },
          ],
        },
        {
          id: 7002,
          name: "ZEBRONICS Micro USB Cable 3.1 A 1 m ZEB-MU300C",
          price: 300,
          originalPrice: 499,
          quantity: 1,
          stock: 10,
          images: { links: ["/cables.png"], imgCount: 1 },
          description:
            "ZEBRONICS Micro USB Cable 3.1 A 1 m ZEB-MU300C is designed for connecting your devices to computers or chargers for fast data transfer.",
          category: "accessories",
          subcategory: "cables",
          brand: "Zebronics",
          reviews: [],
          rating: 0,
          specifications: [
            { key: "Cable Length", value: "2 feet" },
            { key: "Cable Type", value: "USB 3.1" },
            { key: "Connector Type", value: "Micro B" },
          ],
        },

        // Anker Cables
        // {
        //   id: 7003,
        //   name: "SAMSUNG USB Type C Cable 2 A 1 mm EP-DA705BWEGIN",
        //   price: 599,
        //   originalPrice: 999,
        //   quantity: 1,
        // stock: 10,
        //   images: { links: ["/cables.png"], imgCount: 1 },
        //   description:
        //     "The Anker PowerLine II Lightning Cable offers fast charging and long-lasting durability for your Apple devices.",
        //   category: "accessories",
        //   subcategory: "cables",
        //   brand: "SAMSUNG",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Brand", value: "SAMSUNG" },
        //     { key: "Type", value: "USB Type C Cable" },
        //     { key: "Cable Type", value: "Type C 480 Mbps Speed" },
        //     { key: "UTP/STP", value: "NA" },
        //     { key: "Connector 1", value: "1 Pin USB Type A" },
        //     { key: "Connector 2", value: "0 Pin USB" },
        //     { key: "Cable", value: "Standed Round" },
        //     { key: "Ethernet Transmission Standard", value: "NA" },
        //     { key: "Ethernet Channel", value: "USB" },
        //     { key: "Part Number", value: "DA705BWEGIN" },
        //     { key: "Model", value: "EP-DA705BWEGIN" },
        //     { key: "Compatible Devices", value: "Mobile" },
        //     { key: "Color", value: "White" },
        //     {
        //       key: "Suitable For",
        //       value: "Android Phones, Tablets, Power Banks",
        //     },
        //     { key: "Cable Length", value: "1 mm" },
        //   ],
        // },
        // {
        //   id: 7004,
        //   name: "Anker PowerLine+ USB-C to USB 3.0 Cable (6 Feet)",
        //   price: 599,
        //   originalPrice: 799,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/cables.png"],
        //   description:
        //     "Anker PowerLine+ USB-C to USB 3.0 Cable is engineered to support high-speed data transfer and fast charging for USB-C devices.",
        //   category: "accessories",
        //   subcategory: "cables",
        //   brand: "Anker",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Cable Length", value: "6 feet" },
        //     { key: "Cable Type", value: "USB-C to USB 3.0" },
        //     { key: "Material", value: "Braided Nylon" },
        //     { key: "Transfer Speed", value: "Up to 5Gbps" },
        //   ],
        // },

        // // Belkin Cables
        // {
        //   id: 7005,
        //   name: "Belkin 3.5mm Audio Cable (6 Feet)",
        //   price: 699,
        //   originalPrice: 899,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/cables.png"],
        //   description:
        //     "The Belkin 3.5mm Audio Cable provides high-quality audio transmission for connecting your devices to speakers, headphones, and more.",
        //   category: "accessories",
        //   subcategory: "cables",
        //   brand: "Belkin",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Cable Length", value: "6 feet" },
        //     { key: "Cable Type", value: "3.5mm Audio" },
        //     { key: "Connector Type", value: "3.5mm Male" },
        //     { key: "Compatibility", value: "Headphones, Speakers" },
        //   ],
        // },
        // {
        //   id: 7006,
        //   name: "Belkin USB-C to HDMI Adapter Cable (6 Feet)",
        //   price: 1299,
        //   originalPrice: 1499,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/cables.png"],
        //   description:
        //     "The Belkin USB-C to HDMI Adapter Cable allows you to connect your USB-C enabled device to an HDMI display for high-quality video output.",
        //   category: "accessories",
        //   subcategory: "cables",
        //   brand: "Belkin",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Cable Length", value: "6 feet" },
        //     { key: "Cable Type", value: "USB-C to HDMI" },
        //     { key: "Resolution", value: "4K" },
        //     { key: "Compatibility", value: "USB-C Devices" },
        //   ],
        // },

        // // UGREEN Cables
        // {
        //   id: 7007,
        //   name: "UGREEN USB-A to USB-C Cable (10 Feet)",
        //   price: 699,
        //   originalPrice: 899,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/cables.png"],
        //   description:
        //     "UGREEN USB-A to USB-C Cable is perfect for fast charging and data transfer for your USB-C devices with reliable performance.",
        //   category: "accessories",
        //   subcategory: "cables",
        //   brand: "UGREEN",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Cable Length", value: "10 feet" },
        //     { key: "Cable Type", value: "USB-A to USB-C" },
        //     { key: "Transfer Speed", value: "Up to 5Gbps" },
        //     { key: "Compatibility", value: "USB-C Devices" },
        //   ],
        // },
        // {
        //   id: 7008,
        //   name: "UGREEN 3.5mm Audio Cable (10 Feet)",
        //   price: 499,
        //   originalPrice: 699,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/cables.png"],
        //   description:
        //     "UGREEN 3.5mm Audio Cable delivers exceptional sound quality for connecting your audio devices to speakers or headphones.",
        //   category: "accessories",
        //   subcategory: "cables",
        //   brand: "UGREEN",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Cable Length", value: "10 feet" },
        //     { key: "Cable Type", value: "3.5mm Audio" },
        //     { key: "Connector Type", value: "3.5mm Male" },
        //     { key: "Compatibility", value: "Speakers, Headphones" },
        //   ],
        // },
      ],
    },
    {
      id: 8,
      Category: "new-accesories",
      subcategory: "hdd",
      products: [
        // Seagate HDDs
        // {
        //   id: 8001,
        //   name: "kingster Hard Drive 320 GB Laptop Internal Hard Disk Drive (HDD)",
        //   price: 645,
        //   originalPrice: 1999,
        //   quantity: 1,
        // stock: 10,
        //   images: { links: ["/hdd.png"], imgCount: 1 },
        //   description:
        //     "kingster Hard Drive 320 GB Laptop Internal Hard Disk Drive (HDD) provides reliable storage with fast USB 3.0 performance and is portable for on-the-go data storage.",
        //   category: "accessories",
        //   subcategory: "hdd",
        //   brand: "kingster",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Device", value: "Laptop" },
        //     { key: "Device Type", value: "2.5 Inch HDD" },
        //     { key: "Drive Capacity", value: "320 GB" },
        //     { key: "Interface", value: "SATA" },
        //     { key: "Cache Memory", value: "128 MB" },
        //     { key: "Form Factor", value: "2.5 Inch" },
        //     { key: "Brand", value: "kingster" },
        //     {
        //       key: "Model ID",
        //       value:
        //         "320 GB Internal Hard Drive HDD 2.5 Inch SATA 6 Gb/s,5400 RPM,128MB",
        //     },
        //     { key: "Series", value: "Hard Drive" },
        //   ],
        // },
        // {
        //   id: 8002,
        //   name: "kingster Hard Drive 500 GB Laptop Internal Hard Disk Drive (HDD)",
        //   price: 940,
        //   originalPrice: 4000,
        //   quantity: 1,
        // stock: 10,
        //   images: { links: ["/hdd.png"], imgCount: 1 },
        //   description:
        //     "kingster Hard Drive 500 GB Laptop Internal Hard Disk Drive (HDD) offers ample storage space and fast data transfer speeds with USB 3.0 compatibility.",
        //   category: "accessories",
        //   subcategory: "hdd",
        //   brand: "kingster",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Device", value: "Laptop" },
        //     { key: "Device Type", value: "2.5 Inch HDD" },
        //     { key: "Drive Capacity", value: "500 GB" },
        //     { key: "Spin Speed", value: "5400 RPM" },
        //     { key: "Interface", value: "SATA" },
        //     { key: "Cache Memory", value: "128 MB" },
        //     { key: "Transfer Rate", value: "256 Mbps" },
        //     { key: "I/O Transfer Rate", value: "32 Mbps" },
        //     { key: "Data Transfer Rate (To/From Host)", value: "5400 Mbps" },
        //     { key: "Data Transfer Rate (To/From Buffer)", value: "5400 Mbps" },
        //     { key: "Average Latency", value: "4 ms" },
        //     { key: "Non-recoverable Read Error", value: "1" },
        //     { key: "Reliability", value: "3000 (Load/Unload Cycles)" },
        //     { key: "Form Factor", value: "2.5 Inch" },
        //   ],
        // },
        // Western Digital (WD) HDDs
        // {
        //   id: 8003,
        //   name: "TOSHIBA Tcp lap 500 GB Laptop Internal Hard Disk Drive (HDD)",
        //   price: 3499,
        //   originalPrice: 4299,
        //   quantity: 1,
        // stock: 10,
        //   images: { links: ["/hdd.png"], imgCount: 1 },
        //   description:
        //     "TOSHIBA Tcp lap 500 GB Laptop Internal Hard Disk Drive (HDD) provides reliable storage with password protection and automatic backup software.",
        //   category: "accessories",
        //   subcategory: "hdd",
        //   brand: "TOSHIBA",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Device", value: "Laptop" },
        //     { key: "Device Type", value: "2.5 Inch HDD" },
        //     { key: "Drive Capacity", value: "500 GB" },
        //     { key: "Interface", value: "SATA" },
        //     { key: "Form Factor", value: "2.5 Inch" },
        //     { key: "Brand", value: "TOSHIBA" },
        //     { key: "Model ID", value: "Tsdmq01ap" },
        //     { key: "Series", value: "Tcp lap" },
        //   ],
        // },
        // {
        //   id: 8004,
        //   name: "WD 2TB Elements External Hard Drive (USB 3.0)",
        //   price: 4999,
        //   originalPrice: 5999,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/hdd.png"],
        //   description:
        //     "The WD 2TB Elements External Hard Drive provides fast USB 3.0 data transfer speeds and is perfect for storing movies, photos, and documents.",
        //   category: "accessories",
        //   subcategory: "hdd",
        //   brand: "WD",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Storage Capacity", value: "2TB" },
        //     { key: "Connectivity", value: "USB 3.0" },
        //     { key: "Form Factor", value: "Portable" },
        //     { key: "Compatibility", value: "Windows, Mac OS" },
        //   ],
        // },
        // // Toshiba HDDs
        // {
        //   id: 8005,
        //   name: "Toshiba 1TB Canvio Basics Portable External Hard Drive",
        //   price: 3299,
        //   originalPrice: 3799,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/hdd.png"],
        //   description:
        //     "The Toshiba 1TB Canvio Basics Portable External Hard Drive offers simple plug-and-play connectivity with fast USB 3.0 data transfer.",
        //   category: "accessories",
        //   subcategory: "hdd",
        //   brand: "Toshiba",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Storage Capacity", value: "1TB" },
        //     { key: "Connectivity", value: "USB 3.0" },
        //     { key: "Form Factor", value: "Portable" },
        //     { key: "Compatibility", value: "Windows, Mac OS" },
        //   ],
        // },
        // {
        //   id: 8006,
        //   name: "Toshiba 2TB Canvio Basics Portable External Hard Drive",
        //   price: 4799,
        //   originalPrice: 5499,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/hdd.png"],
        //   description:
        //     "The Toshiba 2TB Canvio Basics Portable External Hard Drive provides fast data transfer speeds and offers plenty of storage space for your files.",
        //   category: "accessories",
        //   subcategory: "hdd",
        //   brand: "Toshiba",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Storage Capacity", value: "2TB" },
        //     { key: "Connectivity", value: "USB 3.0" },
        //     { key: "Form Factor", value: "Portable" },
        //     { key: "Compatibility", value: "Windows, Mac OS" },
        //   ],
        // },
        // // Samsung HDDs
        // {
        //   id: 8007,
        //   name: "Samsung 1TB Portable External Hard Drive (USB 3.0)",
        //   price: 3999,
        //   originalPrice: 4499,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/hdd.png"],
        //   description:
        //     "The Samsung 1TB Portable External Hard Drive features a sleek design and provides fast USB 3.0 data transfer speeds for seamless performance.",
        //   category: "accessories",
        //   subcategory: "hdd",
        //   brand: "Samsung",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Storage Capacity", value: "1TB" },
        //     { key: "Connectivity", value: "USB 3.0" },
        //     { key: "Form Factor", value: "Portable" },
        //     { key: "Compatibility", value: "Windows, Mac OS" },
        //   ],
        // },
        // {
        //   id: 8008,
        //   name: "Samsung 2TB Portable External Hard Drive (USB 3.0)",
        //   price: 5999,
        //   originalPrice: 6999,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/hdd.png"],
        //   description:
        //     "The Samsung 2TB Portable External Hard Drive offers large storage capacity and USB 3.0 connectivity for fast data transfer speeds.",
        //   category: "accessories",
        //   subcategory: "hdd",
        //   brand: "Samsung",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Storage Capacity", value: "2TB" },
        //     { key: "Connectivity", value: "USB 3.0" },
        //     { key: "Form Factor", value: "Portable" },
        //     { key: "Compatibility", value: "Windows, Mac OS" },
        //   ],
        // },
      ],
    },
    {
      id: 9,
      Category: "new-accesories",
      subcategory: "ssd",
      products: [
        // Samsung SSDs
        // {
        //   id: 9001,
        //   name: "WESTERN DIGITAL SN 500 GB",
        //   price: 2870,
        //   originalPrice: 3480,
        //   quantity: 1,
        // stock: 10,
        //   images: { links: ["/ssd.png"], imgCount: 1 },
        //   description:
        //     "WESTERN DIGITAL SN 500 GB Laptop Internal Solid State Drive (SSD) offers fast read and write speeds with enhanced reliability and security for a high-performance computing experience.",
        //   category: "accessories",
        //   subcategory: "ssd",
        //   brand: "WESTERN DIGITAL",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Device", value: "Laptop" },
        //     { key: "Device Type", value: "M.2 SSD" },
        //     { key: "Drive Capacity", value: "500 GB" },
        //     { key: "Interface", value: "PCIe NVMe" },
        //     { key: "Form Factor", value: "M.2" },
        //     { key: "Brand", value: "WESTERN DIGITAL" },
        //     { key: "Model ID", value: "WDS500G2G0C" },
        //     { key: "Series", value: "SN" },
        //   ],
        // },
        // {
        //   id: 9002,
        //   name: "Crucial CT500P3SSD8 500 GB",
        //   price: 2900,
        //   originalPrice: 5224,
        //   quantity: 1,
        // stock: 10,
        //   images: { links: ["/ssd.png"], imgCount: 1 },
        //   description:
        //     "Upgrade your PC with 500GB Crucial P3 SSD. The NVMe M.2 SSD lets you feel the difference with super-fast OS boot times and application loads. The 500GB M.2 SSD have a Read speed of 3500 MB/s and Write speed of 1900 MB/s, making this SSD for PC faster than a traditional hard drive for higher performance.",
        //   category: "accessories",
        //   subcategory: "ssd",
        //   brand: "Crucial",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Device", value: "Desktop, Laptop" },
        //     { key: "Device Type", value: "M.2 SSD" },
        //     { key: "Drive Capacity", value: "500 GB" },
        //     { key: "Interface", value: "PCIe NVMe" },
        //     { key: "Form Factor", value: "M.2" },
        //     { key: "Brand", value: "Crucial" },
        //     { key: "Model ID", value: "P3 Pcie 3.0 Nvme M.2 Ssd" },
        //     { key: "Series", value: "CT500P3SSD8" },
        //   ],
        // },
        // Kingston SSDs
        // {
        //   id: 9003,
        //   name: "WESTERN DIGITAL SN 500 GB",
        //   price: 3049,
        //   originalPrice: 12000,
        //   quantity: 1,
        // stock: 10,
        //   images: { links: ["/ssd.png"], imgCount: 1 },
        //   description:
        //     "WESTERN DIGITAL SN 500 GBe SSD offers great speed and value with faster load times for gaming, content creation, and everyday tasks.",
        //   category: "accessories",
        //   subcategory: "ssd",
        //   brand: "WESTERN DIGITAL",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Brand", value: "WESTERN DIGITAL" },
        //     { key: "Model ID", value: "WDS500G3B0E" },
        //     { key: "Series", value: "SN" },
        //     { key: "Device", value: "Laptop" },
        //     { key: "Device Type", value: "M.2 SSD" },
        //     { key: "Drive Capacity", value: "500 GB" },
        //     { key: "Interface", value: "PCIe NVMe" },
        //     { key: "Form Factor", value: "M.2" },
        //   ],
        // },
        // {
        //   id: 9004,
        //   name: "Kingston A2000 1TB NVMe PCIe M.2 Internal SSD",
        //   price: 7999,
        //   originalPrice: 8999,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/ssd.png"],
        //   description:
        //     "The Kingston A2000 1TB NVMe PCIe SSD offers excellent performance with faster boot times and improved game load times for gamers and content creators.",
        //   category: "accessories",
        //   subcategory: "ssd",
        //   brand: "Kingston",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Capacity", value: "1TB" },
        //     { key: "Interface", value: "NVMe PCIe M.2" },
        //     { key: "Read Speed", value: "2200 MB/s" },
        //     { key: "Write Speed", value: "2000 MB/s" },
        //     { key: "Form Factor", value: "M.2" },
        //   ],
        // },
        // // Western Digital (WD) SSDs
        // {
        //   id: 9005,
        //   name: "WD Blue 500GB SATA III Internal SSD",
        //   price: 4499,
        //   originalPrice: 4999,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/ssd.png"],
        //   description:
        //     "The WD Blue 500GB SSD offers fast read and write speeds to improve boot times, application load times, and overall system performance.",
        //   category: "accessories",
        //   subcategory: "ssd",
        //   brand: "WD",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Capacity", value: "500GB" },
        //     { key: "Interface", value: "SATA III" },
        //     { key: "Read Speed", value: "545 MB/s" },
        //     { key: "Write Speed", value: "425 MB/s" },
        //     { key: "Form Factor", value: "2.5-inch" },
        //   ],
        // },
        // {
        //   id: 9006,
        //   name: "WD Blue 1TB SATA III Internal SSD",
        //   price: 8499,
        //   originalPrice: 9499,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/ssd.png"],
        //   description:
        //     "The WD Blue 1TB SATA III SSD offers reliable performance with fast read/write speeds for storing large files, games, and media.",
        //   category: "accessories",
        //   subcategory: "ssd",
        //   brand: "WD",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Capacity", value: "1TB" },
        //     { key: "Interface", value: "SATA III" },
        //     { key: "Read Speed", value: "560 MB/s" },
        //     { key: "Write Speed", value: "530 MB/s" },
        //     { key: "Form Factor", value: "2.5-inch" },
        //   ],
        // },
        // // Crucial SSDs
        // {
        //   id: 9007,
        //   name: "Crucial MX500 500GB SATA III Internal SSD",
        //   price: 4999,
        //   originalPrice: 5499,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/ssd.png"],
        //   description:
        //     "The Crucial MX500 500GB SATA III SSD provides excellent performance with high-speed data transfer and enhanced reliability for all your storage needs.",
        //   category: "accessories",
        //   subcategory: "ssd",
        //   brand: "Crucial",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Capacity", value: "500GB" },
        //     { key: "Interface", value: "SATA III" },
        //     { key: "Read Speed", value: "560 MB/s" },
        //     { key: "Write Speed", value: "510 MB/s" },
        //     { key: "Form Factor", value: "2.5-inch" },
        //   ],
        // },
        // {
        //   id: 9008,
        //   name: "Crucial MX500 1TB SATA III Internal SSD",
        //   price: 9499,
        //   originalPrice: 10999,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/ssd.png"],
        //   description:
        //     "The Crucial MX500 1TB SATA III SSD offers fast read and write speeds and excellent reliability for better system performance and storage.",
        //   category: "accessories",
        //   subcategory: "ssd",
        //   brand: "Crucial",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Capacity", value: "1TB" },
        //     { key: "Interface", value: "SATA III" },
        //     { key: "Read Speed", value: "560 MB/s" },
        //     { key: "Write Speed", value: "510 MB/s" },
        //     { key: "Form Factor", value: "2.5-inch" },
        //   ],
        // },
      ],
    },
    {
      id: 10,
      Category: "new-accesories",
      subcategory: "combos",
      products: [
        {
          id: 10001,
          name: "Zebronics Zeb-Companion 107 Wireless Keyboard and Mouse Combo",
          price: 900,
          originalPrice: 1407,
          quantity: 1,
          stock: 10,
          images: { links: ["/keyboard.png"], imgCount: 1 },
          description:
            "Type fast and accomplish a number of tasks on your personal computer with the Dell KB 216 Wired USB Desktop Keyboard. The full layout of this keyboard features chiclet-style keys for comfortable and efficient typing.",
          category: "accessories",
          subcategory: "combos",
          brand: "Zebronics",
          reviews: [],
          rating: 0,
          specifications: [
            { key: "Type", value: "Wireless" },
            { key: "Connectivity", value: "USB" },
            { key: "Backlit", value: "RGB Lighting" },
            { key: "Compatibility", value: "Windows" },
            { key: "Sales Package", value: "Keyboard, User Manual" },
            { key: "Color", value: "Black" },
          ],
        },
        // {
        //   id: 10002,
        //   name: "Portronics POR 2113 Wireless Laptop Keyboard",
        //   price: 849,
        //   originalPrice: 1999,
        //   quantity: 1,
        // stock: 10,
        //   images: { links: ["/combos.png"], imgCount: 1 },
        //   description:
        //     "Portronics POR 2113 Wireless Laptop Keyboard features Cherry MX Red switches, customizable RGB lighting, and an ultra-modern design.",
        //   category: "accessories",
        //   subcategory: "combos",
        //   brand: "Portronics",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Type", value: "Mechanical" },
        //     { key: "Connectivity", value: "Bluetooth" },
        //     { key: "Backlit", value: "RGB Lighting" },
        //     { key: "Compatibility", value: "Windows, macOS" },
        //     { key: "Sales Package", value: "Keyboard, User Manual" },
        //     { key: "Color", value: "Black" },
        //   ],
        // },

        // HP Combo
        // {
        //   id: 10003,
        //   name: "HP Wireless 280 Combo Keyboard and Mouse",
        //   price: 1299,
        //   originalPrice: 1499,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/mouse + keyboard.png"],
        //   description:
        //     "The HP Wireless 280 Combo includes a wireless keyboard with soft-touch keys and a sleek, responsive mouse for efficient work and entertainment with long battery life.",
        //   category: "accessories",
        //   subcategory: "keyboard + mouse combo",
        //   brand: "HP",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Type", value: "Wireless" },
        //     { key: "Connectivity", value: "2.4GHz Wireless" },
        //     { key: "Keyboard Layout", value: "Full-sized" },
        //     { key: "Mouse DPI", value: "1200" },
        //     {
        //       key: "Battery Life",
        //       value: "15 months (keyboard), 12 months (mouse)",
        //     },
        //   ],
        // },
        // {
        //   id: 10004,
        //   name: "HP 200 Wireless Keyboard and Mouse Combo",
        //   price: 999,
        //   originalPrice: 1199,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/mouse + keyboard.png"],
        //   description:
        //     "The HP 200 Combo is designed for comfort and performance with a wireless keyboard and mouse combo that delivers smooth operation and reliable connectivity.",
        //   category: "accessories",
        //   subcategory: "keyboard + mouse combo",
        //   brand: "HP",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Type", value: "Wireless" },
        //     { key: "Connectivity", value: "2.4GHz Wireless" },
        //     { key: "Keyboard Layout", value: "Standard" },
        //     { key: "Mouse DPI", value: "1000" },
        //     {
        //       key: "Battery Life",
        //       value: "12 months (keyboard), 10 months (mouse)",
        //     },
        //   ],
        // },

        // // Dell Combo
        // {
        //   id: 10005,
        //   name: "Dell KM117 Wireless Keyboard and Mouse Combo",
        //   price: 1399,
        //   originalPrice: 1599,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/mouse + keyboard.png"],
        //   description:
        //     "The Dell KM117 Combo offers a wireless keyboard with chiclet keys and a precise mouse, ideal for everyday computing with seamless connectivity and energy-efficient performance.",
        //   category: "accessories",
        //   subcategory: "keyboard + mouse combo",
        //   brand: "Dell",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Type", value: "Wireless" },
        //     { key: "Connectivity", value: "2.4GHz Wireless" },
        //     { key: "Keyboard Layout", value: "Chiclet" },
        //     { key: "Mouse DPI", value: "1000" },
        //     {
        //       key: "Battery Life",
        //       value: "12 months (keyboard), 10 months (mouse)",
        //     },
        //   ],
        // },
        // {
        //   id: 10006,
        //   name: "Dell KM636 Wireless Keyboard and Mouse Combo",
        //   price: 1499,
        //   originalPrice: 1699,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/mouse + keyboard.png"],
        //   description:
        //     "The Dell KM636 Combo includes a wireless keyboard and mouse with ergonomic design, offering smooth operation for home or office use with extended battery life.",
        //   category: "accessories",
        //   subcategory: "keyboard + mouse combo",
        //   brand: "Dell",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Type", value: "Wireless" },
        //     { key: "Connectivity", value: "2.4GHz Wireless" },
        //     { key: "Keyboard Layout", value: "Full-sized" },
        //     { key: "Mouse DPI", value: "1000" },
        //     {
        //       key: "Battery Life",
        //       value: "18 months (keyboard), 12 months (mouse)",
        //     },
        //   ],
        // },

        // // Razer Combo
        // {
        //   id: 10007,
        //   name: "Razer DeathAdder V2 Mini & Huntsman Mini Combo",
        //   price: 8999,
        //   originalPrice: 9999,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/mouse + keyboard.png"],
        //   description:
        //     "The Razer DeathAdder V2 Mini & Huntsman Mini Combo offers precise, ultra-fast input with optical switches and a responsive mouse for serious gaming enthusiasts.",
        //   category: "accessories",
        //   subcategory: "keyboard + mouse combo",
        //   brand: "Razer",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Type", value: "Wired" },
        //     { key: "Connectivity", value: "USB" },
        //     { key: "Keyboard Layout", value: "60%" },
        //     { key: "Mouse DPI", value: "8500" },
        //     { key: "Switch Type", value: "Optical" },
        //   ],
        // },
        // {
        //   id: 10008,
        //   name: "Razer BlackWidow V3 & DeathAdder Elite Combo",
        //   price: 11999,
        //   originalPrice: 13999,
        //   quantity: 1,
        // stock: 10,
        //   images: {links:["/mouse + keyboard.png"],
        //   description:
        //     "The Razer BlackWidow V3 & DeathAdder Elite Combo provides mechanical switches, customizable RGB lighting, and a precision optical mouse for an ultimate gaming experience.",
        //   category: "accessories",
        //   subcategory: "keyboard + mouse combo",
        //   brand: "Razer",
        //   reviews: [],
        //   rating: 0,
        //   specifications: [
        //     { key: "Type", value: "Wired" },
        //     { key: "Connectivity", value: "USB" },
        //     { key: "Keyboard Layout", value: "Full-sized" },
        //     { key: "Mouse DPI", value: "16000" },
        //     { key: "Switch Type", value: "Mechanical" },
        //   ],
        // },
      ],
    },
    {
      id: 1400,
      Category: "new-accesories",
      subcategory: "speakers",
      products: [
        {
          id: 14001,
          name: "ZEBRONICS Zeb-Pluto 2.0 Multimedia Speaker with Aux Connectivity",
          price: 500,
          originalPrice: 699,
          quantity: 1,
          stock: 10,
          images: { links: ["/speakers.png"], imgCount: 1 },
          description:
            "Type fast and accomplish a number of tasks on your personal computer with the Dell KB 216 Wired USB Desktop Keyboard. The full layout of this keyboard features chiclet-style keys for comfortable and efficient typing.",
          category: "accessories",
          subcategory: "speakers",
          brand: "Zebronics",
          reviews: [],
          rating: 0,
          specifications: [
            { key: "Type", value: "Wired" },
            { key: "Connectivity", value: "USB" },
            { key: "Backlit", value: "RGB Lighting" },
            { key: "Compatibility", value: "Windows" },
            { key: "Sales Package", value: "Keyboard, User Manual" },
            { key: "Color", value: "Black" },
          ],
        },
      ],
    },
    {
      id: 1500,
      Category: "new-accesories",
      subcategory: "adapters",
      products: [
        {
          id: 15001,
          name: "ZEBRONICS ZEB-USB150WF1 WiFi USB Mini Adapter",
          price: 350,
          originalPrice: 400,
          quantity: 1,
          stock: 10,
          images: { links: ["/adapter.png"], imgCount: 1 },
          description:
            "Type fast and accomplish a number of tasks on your personal computer with the Dell KB 216 Wired USB Desktop Keyboard. The full layout of this keyboard features chiclet-style keys for comfortable and efficient typing.",
          category: "accessories",
          subcategory: "adapters",
          brand: "Zebronics",
          reviews: [],
          rating: 0,
          specifications: [
            { key: "Type", value: "Wired" },
            { key: "Connectivity", value: "USB" },
            { key: "Backlit", value: "RGB Lighting" },
            { key: "Compatibility", value: "Windows" },
            { key: "Sales Package", value: "Keyboard, User Manual" },
            { key: "Color", value: "Black" },
          ],
        },
      ],
    },
    {
      id: 1600,
      Category: "new-accesories",
      subcategory: "headphones",
      products: [
        {
          id: 16001,
          name: "ZEBRONICS Zeb-Storm, In-Line Mic",
          price: 700,
          originalPrice: 899,
          quantity: 1,
          stock: 10,
          images: { links: ["/headphones.png"], imgCount: 1 },
          description:
            "Type fast and accomplish a number of tasks on your personal computer with the Dell KB 216 Wired USB Desktop Keyboard. The full layout of this keyboard features chiclet-style keys for comfortable and efficient typing.",
          category: "accessories",
          subcategory: "headphones",
          brand: "Zebronics",
          reviews: [],
          rating: 0,
          specifications: [
            { key: "Type", value: "Wired" },
            { key: "Connectivity", value: "USB" },
            { key: "Backlit", value: "RGB Lighting" },
            { key: "Compatibility", value: "Windows" },
            { key: "Sales Package", value: "Keyboard, User Manual" },
            { key: "Color", value: "Black" },
          ],
        },
      ],
    },
  ],
};
