// import { gallery } from "../assets/images/gallery";
import { ProductData } from "../types";
import { featuredProducts } from "./featuredProducts";

export const productsData: ProductData = {
  products: [
    {
      id: 1,
      subcategory: "Laptops",
      products: featuredProducts,
    },
  ],
  "laptop-types": [
    {
      id: 2001,
      subcategory: "workstation",
      products: [
        {
          id: 200111,
          name: "Lenovo ThinkPad P15v AMD Ryzen 7 Pro 6850H",
          description: "High-performance laptop designed for professionals.",
          price: 108000,
          originalPrice: 158000,
          // discount: +(((55000 - 45000) / 55000) * 100).toFixed(1),
          category: "laptops",
          subcategory: "workstation",
          quantity: 0,
          stock: 10,
          brand: "Lenovo",
          rating: 4.6,
          reviews: [],
          images: {
            links: [
              "/accessories/workstation/Lenovo ThinkPad P15v AMD Ryzen 7 Pro 6850H.png",
            ],
            imgCount: 2,
          },
          specifications: [
            { key: "Brand", value: "Lenovo" },
            { key: "Model Name", value: "ThinkPad P15v Gen 3" },
            { key: "Screen Size", value: "15.6 Inches" },
            { key: "Colour", value: "Black" },
            { key: "CPU Model", value: "AMD Ryzen 7" },
            { key: "RAM Memory Installed Size", value: "32 GB" },
            { key: "Operating System", value: "Windows 11 Pro" },
            { key: "Special Feature", value: "Backlit Keyboard, Thin" },
            { key: "Graphics Card Description", value: "Dedicated" },
            { key: "CPU Speed", value: "3.2 GHz" },
          ],
        },
        {
          id: 200012,
          name: "Dell Precision 7520 Intel Core i7 - 6th Gen",
          description: "High-end laptop with advanced computing power.",
          price: 99990,
          originalPrice: 123990,
          // discount: +(((80000 - 70000) / 80000) * 100).toFixed(1),
          category: "laptops",
          subcategory: "workstation",
          quantity: 1,
          stock: 10,
          brand: "MSI",

          rating: 4.8,
          reviews: [],
          images: {
            links: [
              "/accessories/workstation/Dell Precision 7520 Intel Core i7 - 6th Gen.png",
            ],
            imgCount: 3,
          },
          specifications: [
            { key: "Brand", value: "Dell" },
            { key: "Series", value: "Precesion 7520" },
            { key: "Colour", value: "black" },
            { key: "Form Factor", value: "Laptop" },
            { key: "Standing screen display size", value: "15.6 Inches" },
            { key: "Screen Resolution", value: "1920 x 1080 pixels" },
            { key: "Resolution", value: "Full HD (1920 X 1080) Pixels" },
            { key: "Package Dimensions", value: "20 x 20 x 10 cm; 2.2 kg" },
            { key: "Item model number", value: "Dell Precision 7520" },
            { key: "Processor Brand", value: "Intel" },
            { key: "Processor Type", value: "Core i6 6820HQ" },
            { key: "Processor Speed", value: "2.70 GHz" },
            { key: "Processor Count", value: "1" },
            { key: "RAM Size", value: "16" },
            { key: "Memory Technology", value: "DDR4" },
            { key: "Computer Memory Type", value: "DDR4 SDRAM" },
            { key: "Maximum Memory Supported", value: "32 GB" },
            { key: "Hard Drive Size", value: "512 GB" },
            { key: "Hard Disk Description", value: "SSD" },
            { key: "Audio Details", value: "Headphones" },
            { key: "Graphics Chipset Brand", value: "NVIDIA" },
            { key: "Graphics Card Description", value: "Dedicated" },
            { key: "Graphics RAM Type", value: "DDR SDRAM" },
            { key: "Graphics Card Ram Size", value: "4 GB" },
            { key: "Graphics Card Interface", value: "Integrated" },
            { key: "Connectivity Type", value: "Wi-Fi" },
            { key: "Wireless Type", value: "802.11bgn" },
            { key: "Number of USB 3.0 Ports", value: "4" },
            { key: "Optical Drive Type", value: "No Optical Drive" },
            { key: "Operating System", value: "Windows 10 Pro" },
            { key: "Are Batteries Included", value: "No" },
            {
              key: "Included Components",
              value: "Adaptor, Laptop, power Cable",
            },
            { key: "Item Weight", value: "2 kg 200 g" },
          ],
        },
      ],
    },
    {
      id: 2002,
      subcategory: "programming",
      products: [
        {
          id: 11001,
          name: "Lenovo ThinkPad L480 Core i5 8th Gen",
          price: 21200,
          originalPrice: 25999,
          stock: 30,
          quantity: 1,

          images: {
            links: [
              "/accessories/laptop-types/Lenovo ThinkPad L480 Core i5 8th Gen.png",
            ],
            imgCount: 3,
          },
          description:
            "Business-class laptop with Intel Core i5 8th Gen, 8GB RAM, 512GB SSD, and a 14-inch FHD display.",
          category: "computers",
          subcategory: "laptop-types",
          brand: "Lenovo",
          reviews: [],
          rating: 4.4,
          specifications: [
            { key: "Processor", value: "Intel Core i5 8th Gen" },
            { key: "RAM", value: "8GB" },
            { key: "Storage", value: "512GB SSD" },
            { key: "Display", value: "14-inch FHD (1920 x 1080)" },
            { key: "Graphics", value: "Intel UHD Graphics 620" },
            { key: "Operating System", value: "Windows 10 Pro" },
            { key: "Weight", value: "1.68 Kg" },
            { key: "Battery", value: "Up to 3 hours" },
            { key: "Ports", value: "USB-C, USB 3.0, HDMI, Ethernet" },
            { key: "Keyboard", value: "Backlit, spill-resistant" },
            {
              key: "Additional Features",
              value: "Spill-resistant keyboard, fingerprint reader",
            },
          ],
        },
        {
          id: 11005,
          name: "Lenovo Thinkpad L470 Business Laptop i5 7th gen",
          price: 18999,
          stock: 30,
          originalPrice: 23999,
          quantity: 1,

          images: {
            links: [
              "/accessories/laptop-types/Lenovo Thinkpad L470 Business Laptop i5 7th gen.png",
            ],
            imgCount: 3,
          },
          description:
            "High-performance business laptop with Intel Core i5 8th Gen, 8GB RAM, 256GB SSD, and a stunning 14-inch WQXGA display.",
          category: "computers",
          subcategory: "laptop-types",
          brand: "Lenovo",
          reviews: [],
          rating: 4.7,
          specifications: [
            { key: "Standing Screen Display Size", value: "14 Inches" },
            { key: "Screen Resolution", value: "1366 x 768 pixels" },
            { key: "Max Screen Resolution", value: "1366x768 Pixels" },
            { key: "Processor", value: "Core i5 7th Gen" },
            { key: "RAM", value: "8 GB DDR4" },
            { key: "Memory Speed", value: "2.3 GHz" },
            { key: "Hard Drive", value: "500 GB HDD" },
            { key: "Graphics Coprocessor", value: "Intel HD Graphics 520" },
            { key: "Chipset Brand", value: "Intel" },
            { key: "Card Description", value: "Integrated" },
            { key: "Graphics Card RAM Size", value: "4 GB" },
            { key: "Wireless Type", value: "Bluetooth" },
            { key: "Number of USB 3.0 Ports", value: "3" },
            { key: "Average Battery Life (in hours)", value: "13 Hours" },
            { key: "Brand", value: "Lenovo" },
            { key: "Series", value: "Lenovo Thinkpad" },

            { key: "Operating System", value: "Windows 10 Pro" },
            { key: "Item Weight", value: "3.59 pounds" },
            { key: "Product Dimensions", value: "3.2 x 12 x 16.7 inches" },
            { key: "Item Dimensions (LxWxH)", value: "3.2 x 12 x 16.7 inches" },
            { key: "Color", value: "Black" },
            { key: "Processor Brand", value: "Intel" },

            {
              key: "Batteries",
              value: "1 Lithium Polymer batteries required. (included)",
            },
          ],
        },
        {
          id: 11006,
          name: "Lenovo Thinkpad L460 Business Laptop i5 6th gen",
          price: 16999,
          stock: 30,
          originalPrice: 21999,
          quantity: 1,

          images: {
            links: [
              "/accessories/laptop-types/Lenovo Thinkpad L460 Business Laptop i5 6th gen.png",
            ],
            imgCount: 3,
          },
          description:
            "High-performance business laptop with Intel Core i5 8th Gen, 8GB RAM, 256GB SSD, and a stunning 14-inch WQXGA display.",
          category: "computers",
          subcategory: "laptop-types",
          brand: "Lenovo",
          reviews: [],
          rating: 4.7,
          specifications: [
            { key: "Standing Screen Display Size", value: "14 Inches" },
            { key: "Screen Resolution", value: "1366 x 768 pixels" },
            { key: "Max Screen Resolution", value: "1366x768 Pixels" },
            { key: "Processor", value: "Core i5 6th Gen" },
            { key: "RAM", value: "8 GB DDR4" },
            { key: "Memory Speed", value: "2.3 GHz" },
            { key: "Hard Drive", value: "500 GB HDD" },
            { key: "Graphics Coprocessor", value: "Intel HD Graphics 520" },
            { key: "Chipset Brand", value: "Intel" },
            { key: "Card Description", value: "Integrated" },
            { key: "Graphics Card RAM Size", value: "4 GB" },
            { key: "Wireless Type", value: "Bluetooth" },
            { key: "Number of USB 3.0 Ports", value: "3" },
            { key: "Average Battery Life (in hours)", value: "3 Hours" },
            { key: "Brand", value: "Lenovo" },
            { key: "Series", value: "Lenovo Thinkpad" },

            { key: "Operating System", value: "Windows 10 Pro" },
            { key: "Item Weight", value: "3.59 pounds" },
            { key: "Product Dimensions", value: "3.2 x 12 x 16.7 inches" },
            { key: "Item Dimensions (LxWxH)", value: "3.2 x 12 x 16.7 inches" },
            { key: "Color", value: "Black" },
            { key: "Processor Brand", value: "Intel" },

            {
              key: "Batteries",
              value: "1 Lithium Polymer batteries required. (included)",
            },
          ],
        },
      ],
    },
    // {
    //   id: 2002,
    //   subcategory: "gaming",
    //   products: [
    //     {
    //       id: 20021,
    //       name: "ASUS TUF Gaming A15, AMD Ryzen 7 7435Hs, 15.6-Inch, FHD 144Hz, Gaming Laptop",
    //       description:
    //         "Top-tier gaming laptop for the ultimate gaming experience.",
    //       price: 85000,
    //       originalPrice: 100000,
    //       // discount: +(((100000 - 85000) / 100000) * 100).toFixed(1),
    //       category: "laptops",
    //       subcategory: "gaming",
    //       quantity: 1,
    // stock: 10,
    //       brand: "ASUS",
    //       rating: 4.9,
    //       reviews: [],
    //       images: {
    //         links: [
    //           "/accessories/gaming/ASUS TUF Gaming A15, AMD Ryzen 7 7435Hs, 15.6-Inch, FHD 144Hz, Gaming Laptop.png",
    //         ],
    //         imgCount: 2,
    //       },
    //       specifications: [
    //         { key: "Brand", value: "ASUS" },
    //         {
    //           key: "Manufacturer",
    //           value:
    //             "ASUS, TECH FRONT (CHONGQING) Computer Co. Ltd, NO 18, Zongbao Road, Shapingba Dist, Chongquing, China",
    //         },
    //         { key: "Series", value: "TUF Gaming F15" },
    //         { key: "Colour", value: "Graphite Black, R7 | RTX 3050" },
    //         { key: "Form Factor", value: "Ultra-Portable" },
    //         { key: "Item Height", value: "43.2 Centimeters" },
    //         { key: "Item Width", value: "31 Centimeters" },
    //         { key: "Standing screen display size", value: "15.6 Inches" },
    //         { key: "Screen Resolution", value: "1920 x 1080 pixel" },
    //         { key: "Resolution", value: "1920 x 1080 Pixels" },
    //         { key: "Product Dimensions", value: "10.4 x 31 x 43.2 cm; 2.3 kg" },
    //         {
    //           key: "Batteries",
    //           value: "1 Lithium Ion batteries required. (included)",
    //         },
    //         { key: "Item model number", value: "FA506NCR-HN054W" },
    //         { key: "Processor Brand", value: "AMD" },
    //         { key: "Processor Type", value: "AMD Ryzen 7" },
    //         { key: "Processor Speed", value: "3.1 GHz" },
    //         { key: "Processor Count", value: "8" },
    //         { key: "RAM Size", value: "16" },
    //         { key: "Memory Technology", value: "DDR5" },
    //         { key: "Computer Memory Type", value: "DDR5 RAM" },
    //         { key: "Maximum Memory Supported", value: "32 GB" },
    //         { key: "Hard Drive Size", value: "512 GB" },
    //         { key: "Hard Disk Description", value: "SSD" },
    //         { key: "Audio Details", value: "Headphones" },
    //         { key: "Speaker Description", value: "DTS Software" },
    //         { key: "Graphics Coprocessor", value: "NVIDIA GeForce RTX 3050" },
    //         { key: "Graphics Chipset Brand", value: "NVIDIA" },
    //         { key: "Graphics Card Description", value: "Dedicated" },
    //         { key: "Graphics RAM Type", value: "GDDR6" },
    //         { key: "Graphics Card Ram Size", value: "4 GB" },
    //         { key: "Graphics Card Interface", value: "PCI Express" },
    //         { key: "Connectivity Type", value: "Wi-Fi" },
    //         { key: "Voltage", value: "240 Volts" },
    //         { key: "Optical Drive Type", value: "No Optical Storage" },
    //         { key: "Operating System", value: "Windows 11 Home" },
    //         { key: "Are Batteries Included", value: "Yes" },
    //         { key: "Lithium Battery Energy Content", value: "48 Watt Hours" },
    //         { key: "Number of Lithium Ion Cells", value: "3" },
    //         {
    //           key: "Included Components",
    //           value: "Laptop, Adapter & User Manuals",
    //         },
    //         { key: "Country of Origin", value: "China" },
    //         { key: "Item Weight", value: "2 kg 300 g" },
    //       ],
    //     },
    //     {
    //       id: 20022,
    //       name: "Acer Nitro V Gaming Laptop 13th Gen Intel Core i5-13420H with RTX 4050 Graphics",
    //       description:
    //         "Immersive gaming with smooth gameplay and top graphics.",
    //       price: 95000,
    //       originalPrice: 110000,
    //       // discount: +(((110000 - 95000) / 110000) * 100).toFixed(1),
    //       category: "laptops",
    //       subcategory: "gaming",
    //       quantity: 1,
    // stock: 10,
    //       brand: "Acer",

    //       rating: 4.8,
    //       reviews: [],
    //       images: { links: [
    //         "/accessories/gaming/Acer Nitro V Gaming Laptop 13th Gen Intel Core i5-13420H with RTX 4050 Graphics.png",
    //       ], imgCount: 1 },
    //       specifications: [
    //         { key: "Processor", value: "AMD Ryzen 9" },
    //         { key: "RAM", value: "16 GB" },
    //         { key: "Storage", value: "1 TB SSD" },
    //         { key: "Graphics", value: "NVIDIA GeForce RTX 3070" },
    //         { key: "Screen Size", value: "15.6 inches" },
    //         { key: "Battery Life", value: "9 hours" },
    //         { key: "Operating System", value: "Windows 10 Pro" },
    //         { key: "Color", value: "Red" },
    //       ],
    //     },
    //     {
    //       id: 20023,
    //       name: "Speedster GX",
    //       description: "Sleek and powerful laptop for serious gamers.",
    //       price: 70000,
    //       originalPrice: 85000,
    //       // discount: +(((85000 - 70000) / 85000) * 100).toFixed(1),
    //       category: "",
    //       subcategory: "laptops",
    //       quantity: 1,
    // stock: 10,
    //       brand: "",
    //       rating: 4.7,
    //       reviews: [],
    //       images: { links: [gallery[4]], imgCount: 1 },
    //       specifications: [
    //         { key: "Processor", value: "Intel Core i7" },
    //         { key: "RAM", value: "16 GB" },
    //         { key: "Storage", value: "512 GB SSD" },
    //         { key: "Graphics", value: "NVIDIA GeForce GTX 1660 Ti" },
    //         { key: "Screen Size", value: "15.6 inches" },
    //         { key: "Battery Life", value: "7 hours" },
    //         { key: "Operating System", value: "Windows 10 Home" },
    //         { key: "Color", value: "Black" },
    //       ],
    //     },
    //   ],
    // },
  ],
};
